### ISSUE TITLE
./bootstrap.sh fails with " possibly undefined macro: AC_CONFIG_MACRO_DIRS"

### ISSUE THREAD

**Issue by jinyeluo** [openvenues/libpostal#116]
I am on Red Hat Enterprise Linux Server release 5.8 (Tikanga)

"sudo yum install snappy snappy-devel autoconf automake libtool pkgconfig" was successful with error. 

Here is the full msg when run "bootstrap.sh".

-sh-3.2$ ./bootstrap.sh
configure.ac:6: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:15: error: possibly undefined macro: AC_PROG_CC_C99
configure.ac:36: error: possibly undefined macro: AC_TYPE_INT16_T
configure.ac:37: error: possibly undefined macro: AC_TYPE_INT32_T
configure.ac:38: error: possibly undefined macro: AC_TYPE_INT64_T
configure.ac:39: error: possibly undefined macro: AC_TYPE_INT8_T
configure.ac:42: error: possibly undefined macro: AC_TYPE_SSIZE_T
configure.ac:43: error: possibly undefined macro: AC_TYPE_UINT16_T
configure.ac:44: error: possibly undefined macro: AC_TYPE_UINT32_T
configure.ac:45: error: possibly undefined macro: AC_TYPE_UINT64_T
configure.ac:46: error: possibly undefined macro: AC_TYPE_UINT8_T
autoreconf: /usr/bin/autoconf failed with exit status: 1

(Sorry, I haven't been doing C++ for centuries)

My team with 10+ developers are doing nothing but name/address parsing/matching. So there is a good opportunity my team can use the library and you will have our support.

**Comment by thatdatabaseguy** [comment]
Hm, what was the yum error? It sounds like one of the required packages didn't install correctly. I'd look up whatever that error was and see if e.g. maybe there are slightly different package names for RHEL. If you find that's the case, let me know and I'll update the install docs.

**Comment by jinyeluo** [comment]
I should have said: "sudo yum install snappy snappy-devel autoconf automake libtool pkgconfig" was successful # without error.

**Comment by jinyeluo** [comment]
looks like snappy only available on v6 and I have v5.8.

I will try to upgrade the server, but that shouldn't fail autoreconf

**Comment by thatdatabaseguy** [comment]
Yeah, the autotools packages are definitely not up-to-date, so may not have the expected autoconf macros (it's kind of an old RHEL version so probably will have to either upgrade or find RPMs from somewhere other than the yum repos). These are the versions I'm using for reference:

- **autoconf**: 2.69
- **automake**: 1.15
- **libtool**: 2.4.2
- **pkg-config**: 0.29

Snappy should also be available as an RPM outside of yum, or can be downloaded and built from source if needed: http://google.github.io/snappy/.
