### ISSUE TITLE
Suggestions to improve the readme

### ISSUE THREAD

**Issue by lukeholman** [openvenues/libpostal#117]
Thanks for developing this really useful project!

I'm struggling to do some of the basics, and I was hoping you could update the readme for more novice programmers. Basically I'd love a worked example of how to feed in more than one address at a time (and ideally, how to write the output to a file), e.g. via the command line.

Here's what I've managed so far, using the current instructions (to give you an idea of how inexperienced people can screw it up):

I followed the instructions and typed ./address_parser at the command line (I'm on Mac) to access the interactive shell, and if I type in single addresses, it parses them very nicely. 

However, I can't get it to parse a load of addresses in one go. I assumed the way to do this would be to write a bash script, something like:

```
cd libpostal
cd src
./address_parser
18 Smith Road, London, UK
35 King St, New York, NY, USA
123 Example Lane, China
```

But that doesn't work. I also can't run any commands that would write the outputs to disk while inside the parser (it just assumes the commands are addresses).

I also tried to use libpostal via R. However it seems to perform so slowly in R as to be useless for any big jobs. It takes 30 seconds to parse the two addresses provided in the example for postal_parse:

```
> system.time(postal_parse(c("Quatre vignt douze Ave des Champs-Élysées",
"sept rue des freres lumiere, Rueil-Malmaison")))
   user  system elapsed 
  1.634   2.088  30.412
```

Is the R package known to be this slow, or has something gone wrong on my end?

**Comment by thatdatabaseguy** [comment]
Hi Luke,

So the command-line parser doesn't really have a batch mode. It's easy to add but the JSON it outputs would be slightly more unwieldy than the command line interface's pseudo-JSON to preserve ordering of the components (somethings like "Red Lion Pub, 123 High Street, Hadrian House, London" would return ```[{"label": "house", "value": "red lion pub"}, {"label": "house_number", "value": "123"}, {"label": "road", "value": "high street"}, {"label": "house", "value": "hadrian house"}, {"label": "city", "value": "london"}]``` - also note that the label ```house``` was repeated twice, so any one-value-per-component expectation won't cut it for some of the more complex addresses).

As far as the R binding, I doubt it's actually that slow (haven't profiled the R binding though, just helped the author get it working, but still it's a thin wrapper and libpostal should take microseconds, not seconds). There's a one-time setup cost to load the libpostal models from disk into memory. This should [only be called once](https://github.com/Ironholds/poster/tree/master/R/zzz.R) the first time the extension is loaded, so it's possible that the 30 second call above is taking setup cost into account, and that would be amortized over a larger data set or repeated calls to the same function. If making the call a second time is equally slow or it scales linearly with the number of addresses in the input, that might be an issue with the R binding and worth flagging on that repo.

./al

**Comment by lukeholman** [comment]
Hi there,

Thanks for the feedback! I checked a slightly longer call to the R function, and it does indeed seem to scale linearly with the number of addresses that one adds to the call:

```
> system.time(postal_parse(c("Quatre vignt douze Ave des Champs-Élysées",
+                            "sept rue des freres lumiere, Rueil-Malmaison",
+                            "Red Lion Pub, 123 High Street, Hadrian House, London",
+                            "123 Example Lane, China",
+                            "18 Smith Road, London, UK")))
   user  system elapsed 
  3.820   4.765  83.713 
```

So, I'll flag it on that repo. Do you happen to know which of the other bindings are working properly? Python maybe?

Cheers

**Comment by thatdatabaseguy** [comment]
Ohhhhh I see, those aren't the official R bindings. A user wrote that version as a stopgap measure before the official R bindings were released. That implementation is indeed linear in the number of setup/teardown calls because it's pure R, just calls the command client and parses the output.

The correct Rstats bindings (listed in this repo's docs) call the C API directly and can be found here: https://github.com/ironholds/poster.

**Comment by lukeholman** [comment]
Thanks for the reply, that clears things up. 

The poster package almost works! The normaliser works great (and it's lightning fast), but the parser seems to be broken unfortunately (it's already been neatly flagged on that page). 

Thanks for the help!
