### ISSUE TITLE
Multiple issues with OSX configure

### ISSUE THREAD

**Issue by Ironholds** [openvenues/libpostal#118]
> Olivers-MacBook-Pro:libpostal ironholds$ ./configure --datadir= Users/ironholds/datasets
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: Users/ironholds/datasets
configure: error: expected an absolute directory name for --datadir:

What am I doing wrong?

**Comment by thatdatabaseguy** [comment]
Oh, datadir has to be an absolute directory name, should be: ```--datadir=/Users/ironholds/datasets```

**Comment by Ironholds** [comment]
Perfect!
