### ISSUE TITLE
Build issues with Snappy on OSX 10.11

### ISSUE THREAD

**Issue by riordan** [openvenues/libpostal#12]
El Capitan seems to be triggering build issues involving Snappy.

Running `brew install snappy` works without a problem (and seems to pass its internal tests), but then when we run `./configure` it will trigger:

```
checking for library containing snappy_compress... no
configure: error: Could not find snappy
```

Others on the team seem to have this same problem. Is there an easy way I can test if GCC can find the library?

Partially I'm flagging this here because I haven't seen any [related open issues at homebrew](https://github.com/Homebrew/homebrew/search?o=desc&q=snappy&s=created&type=Issues&utf8=%E2%9C%93).

In the interim, I threw together a quick [vagrant image](https://github.com/riordan/vagrant-libpostal) for working with Libpostal and all the bindings.

**Comment by thatdatabaseguy** [comment]
Hm, I've actually using El Capitan as well, haven't come across that issue, although my snappy installation may be from a backup.

Do you see the file libsnappy.dylib in /usr/local/lib?

P.S. :+1: on the Vagrant image, that's awesome

**Comment by riordan** [comment]
The Dylib is there which is what makes it all the more strange...

**Comment by thatdatabaseguy** [comment]
Ok, this sounds like a path issue. Try:

```
./configure LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/lib" --datadir=[your data dir]
```

**Comment by stephenkhess** [comment]
The ./configure step now works but `make` fails:

```
admins-MacBook-Pro-3% ll /usr/local/include/snappy*
-rw-r--r--@ 1 stephenhess  admin  5393 Dec 21 14:59 /usr/local/include/snappy-c.h
-rw-r--r--@ 1 stephenhess  admin  4931 Dec 21 14:59 /usr/local/include/snappy-sinksource.h
-rw-r--r--  1 stephenhess  admin  3173 Dec 21 14:59 /usr/local/include/snappy-stubs-public.h
-rw-r--r--@ 1 stephenhess  admin  8640 Dec 21 14:59 /usr/local/include/snappy.h
```

**Comment by thatdatabaseguy** [comment]
Ok, the changes I just pushed should resolve, although I have not been able to reproduce the issue. You should also be able to run configure without adding LDFLAGS/CFLAGS this time.

Let me know if that fixes it on your end.

**Comment by stephenkhess** [comment]
Builds fine now, thanks!

**Comment by thatdatabaseguy** [comment]
Nice! np
