### ISSUE TITLE
Österreich (Austria) not detected as country

### ISSUE THREAD

**Issue by dominikkukacka** [openvenues/libpostal#128]
As I understood it libpostal should be able to analyse all languages.
But it fails to detect the german translation of Austria (Österreich), the english one works.

It seems to be thinking it is of component type house.

**Comment by thatdatabaseguy** [comment]
Maybe not _all_ languages yet (there are hundreds), but 60 of the most frequently used languages on street signs. Also remember that libpostal is around 99% accurate, but still gets the wrong answer 1% of the time, so can't ever be expected it to be perfect, but yes, some of the errors it makes seem annoying/obvious/avoidable.

There's been a lot of work done on place names in a branch called [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) which includes updates to both the model code itself and the training data it uses. That branch is still a work-in-progress and can't be merged into master yet, but there is an intermediate version of the new model that is backward compatible with master. That can be found at: https://libpostal.s3.amazonaws.com/mapzen_sample/parser_full.tar.gz. To use it (doesn't require switching branches or anything, it's the same model in master trained on more/better data), just unpack the contents of the tarball into $DATA_DIR/libpostal/address_parser where $DATA_DIR is whatever you passed in during configure, default is /usr/local/share.

In my brief tests that model got Österreich correct.

**Comment by dominikkukacka** [comment]
Perfect! Any estimate when this will be merged?

**Comment by thatdatabaseguy** [comment]
Not yet. There's a bit of trial-and-error/experimentation involved in ensuring the improvements don't break existing test cases. But will update all relevant issues when it's ready.

**Comment by thatdatabaseguy** [comment]
Can still download/unpack the above though and it'll work seamlessly with the master checkout.

**Comment by dominikkukacka** [comment]
Awesome! Thanks for the fast reply and the help!

**Comment by thatdatabaseguy** [comment]
@dominikkukacka libpostal 1.0 was released earlier today. Should handle just about every variation of Österreich/Austria:

```
> Österreich

Result:

{
  "country": "österreich"
}

> Oesterreich

Result:

{
  "country": "oesterreich"
}

> Osterreich

Result:

{
  "country": "osterreich"
}

> Austria

Result:

{
  "country": "austria"
}

> AT

Result:

{
  "country": "at"
}

> AUT

Result:

{
  "country": "aut"
}
```
