### ISSUE TITLE
Installation errors when trying to make on parser-data branch

### ISSUE THREAD

**Issue by nsutcliffe** [openvenues/libpostal#129]
I am trying to use the parser-data branch, but am getting installation errors when running the make command. I've attached the log, but the first place it seems to error is here:

`trie_search.c:777:14: error: conflicting types for 'cstring_array_get_phrase'`

I can see in GIT that there hasn't been any changes to trie_search.c and trie_search.h for some time, so suspect that the problem is the way in which we are installing; are there some flags that should be provided to get this to install?

[make.txt](https://github.com/openvenues/libpostal/files/580624/make.txt)

**Comment by thatdatabaseguy** [comment]
parser-data is my development branch and most of the recent work has been on the Python side to construct a larger/better training set for libpostal. The changes to the C code are in progress, and some are uncommitted.

Recommending that people use the new model files for the moment, not parser-data itself.

There is an intermediate version of the new model that is backward compatible with master. That can be found at: https://libpostal.s3.amazonaws.com/mapzen_sample/parser_full.tar.gz. To use it (doesn't require switching branches or anything, it's the same model in master trained on more/better data), just unpack the contents of the tarball into $DATA_DIR/libpostal/address_parser where $DATA_DIR is whatever you passed in during configure, default is /usr/local/share.

**Comment by nsutcliffe** [comment]
Thanks, I'll try using the new model files!
