### ISSUE TITLE
Possible regression

### ISSUE THREAD

**Issue by b-may** [openvenues/libpostal#130]
I am using MapZen search and running into several address parsing issues. In issue https://github.com/pelias/pelias/issues/464, @orangejulius and @trescube said there may be a regression in libpostal and suggested posting an issue here to notify / investigate.

**Comment by thatdatabaseguy** [comment]
Responded on pelias/pelias#464

**Comment by thatdatabaseguy** [comment]
Hey @b-may, libpostal 1.0 was released earlier today. The new parser correctly identifies all the components of the address you posted, and in general implements the changes I mentioned on the Pelias repo, abbreviating things like "Fort"=>"Ft" for smaller cities, etc.

```
> 103 BEAL PKWY SE, FT WALTON BEACH, FL

Result:

{
  "house_number": "103",
  "road": "beal pkwy se",
  "city": "ft walton beach",
  "state": "fl"
}
```
