### ISSUE TITLE
Need help running ./libpostal

### ISSUE THREAD

**Issue by rahulmidha31** [openvenues/libpostal#131]
Hi,

My address parser seems to work. But while running the ./libpostal script i get the error below.

./libpostal "<address>"
ERR   language_classifier not loaded, run libpostal_setup_language_classifier()
   at classify_languages (language_classifier.c:63) errno: No such file or directory

Can somebody help as to whats the issue here?

**Comment by thatdatabaseguy** [comment]
That just means that not all the files downloaded correctly. Try removing the datadir and re-running ```make```. Look for any errors during the download.

**Comment by rahulmidha31** [comment]
Worked. Thanks.
