### ISSUE TITLE
Cross-compilation fails on undefined reference to `rpl_realloc'

### ISSUE THREAD

**Issue by rinigus** [openvenues/libpostal#134]
When compiling libpostal on Sailfish SDK for ARM, a cross-compilation is used. Compilation fails with 

```
/bin/sh ../libtool  --tag=CC   --mode=link gcc -std=gnu99 -Wfloat-equal -Wpointer-arith -DLIBPOSTAL_DATA_DIR='"/usr/local/share/libpostal"' -O3 -Wfloat-equal -Wpointer-arith -DLIBPOSTAL_DATA_DIR='"/usr/local/share/libpostal"'  -L/usr/local/lib -o libpostal libpostal-main.o libpostal-json_encode.o libpostal.la -lm -lsnappy
libtool: link: gcc -std=gnu99 -Wfloat-equal -Wpointer-arith -DLIBPOSTAL_DATA_DIR=\"/usr/local/share/libpostal\" -O3 -Wfloat-equal -Wpointer-arith -DLIBPOSTAL_DATA_DIR=\"/usr/local/share/libpostal\" -o .libs/libpostal libpostal-main.o libpostal-json_encode.o  -L/usr/local/lib ./.libs/libpostal.so -lm /usr/local/lib/libsnappy.so -Wl,-rpath -Wl,/usr/local/lib
libpostal-main.o: In function `main':
main.c:(.text.startup+0x15c): undefined reference to `rpl_realloc'
main.c:(.text.startup+0x1ea): undefined reference to `rpl_malloc'
main.c:(.text.startup+0x1fe): undefined reference to `rpl_malloc'
```

To overcome it, one can define 

```
ac_cv_func_malloc_0_nonnull=yes
ac_cv_func_realloc_0_nonnull=yes
```

in a shell before `./configure`. I hope that there is a more elegant way to fix it in configuration scripts.

**Comment by thatdatabaseguy** [comment]
libpostal is primarily tested on are Mac OSX and Ubuntu. It typically works fine on most other flavors of Linux with a few modifications, but for platform-specific issues, I usually defer to users who have the relevant machines to test on.

If you're comfortable with autoconf (or are like me and Google "[issue] autoconf" until something minimally works and you can stop thinking about autoconf), feel free to add the relevant checks to [configure.ac](https://github.com/openvenues/libpostal/blob/master/configure.ac). Happy to accept pull requests.

**Comment by rinigus** [comment]
Fair enough. I'll look around and will try to fix it.

**Comment by rinigus** [comment]
I guess this can be closed now
