### ISSUE TITLE
Repeating download (although no data change)

### ISSUE THREAD

**Issue by bradh** [openvenues/libpostal#143]
Each time I run make, I get a new data download (which is slow, and probably not good for your S3 bill - sorry about that).

I did some (limited) investigation, and it looks like S3 returns 200 (instead of 304) if the requested date is in the future.
```

bradh@ornata:~/devel/libpostal$ curl -sI http://libpostal.s3.amazonaws.com/libpostal_data.tar.gz -z "26 Dec 2016 00:24:00 GMT" --remote-time -w %{http_code}
HTTP/1.1 304 Not Modified
x-amz-id-2: bErSTLGl4I/I3/TFiM50u2nNqH9lbOTyd1490O2tYN2t1YNkSmckoWL5YlrMnZNmdj7ZYLpRXms=
x-amz-request-id: B4A34E9B09510A4C
Date: Mon, 26 Dec 2016 00:24:09 GMT
Last-Modified: Fri, 07 Oct 2016 00:46:44 GMT
ETag: "b169a6f1f203de9b2906cd163e3f28b8-2"
Server: AmazonS3

304
bradh@ornata:~/devel/libpostal$ curl -sI http://libpostal.s3.amazonaws.com/libpostal_data.tar.gz -z "26 Dec 2016 00:26:00 GMT" --remote-time -w %{http_code}
HTTP/1.1 200 OK
x-amz-id-2: wlbxqXbFOSmGCNs7fzOdKpizoyQgZZPnM7ZHmbb21zkQJHfiTJ56Rhh9uk3JxHwHkBaHQAlXxWM=
x-amz-request-id: 25450EE13EF28DDA
Date: Mon, 26 Dec 2016 00:24:15 GMT
Last-Modified: Fri, 07 Oct 2016 00:46:44 GMT
ETag: "b169a6f1f203de9b2906cd163e3f28b8-2"
Accept-Ranges: bytes
Content-Type: application/x-tar
Content-Length: 10669429
Server: AmazonS3

200
```
(as to why we send addresses in the future, that looks like a possible bug where curl or S3 doesn't parse the timezone correctly - I'm at UTC+11).

The cleanest solution is probably to just use UTC as the date reference. Will send a PR for that.

**Comment by thatdatabaseguy** [comment]
Was under the impression that this was solved in #38 by adding ```-u``` in the inner call to ```date``` as the others are just relative date math.

The dates pasted above are literals. Are those obtained using method as in libpostal_data? Also, are the housekeeping files ($LIBPOSTAL_DATA_DIR/last_updated*) storing UTC? If not, it might be something else that's causing the repeat download.

**Comment by bradh** [comment]
The outer call defaults  to local, and that is what I see in the housekeeping files.

```
bradh@ornata:~/devel/libpostal/src$ cat /usr/local/share/libpostal/last_updated
Mon Dec 26 20:20:47 AEDT 2016
```

Using the same snippet as in `libpostal_data`:
```
bradh@ornata:~/devel/libpostal/src$ echo $(date -d "$(date -d "@$(date -ur /usr/local/share/libpostal/last_updated +%s)") + 1 second")
Mon Dec 26 20:20:47 AEDT 2016
```

Adding outer -u per my pull request:
```
bradh@ornata:~/devel/libpostal/src$ echo $(date -ud "$(date -ud "@$(date -ur /usr/local/share/libpostal/last_updated +%s)") + 1 second")
Mon Dec 26 09:20:47 UTC 2016
```

And substituting those into the curl call used in `libpostal_data`:
```
bradh@ornata:~/devel/libpostal/src$ curl -sI http://libpostal.s3.amazonaws.com/libpostal_data.tar.gz -z "Mon Dec 26 20:20:47 AEDT 2016" --remote-time -w %{http_code} -o /dev/null
200
bradh@ornata:~/devel/libpostal/src$ curl -sI http://libpostal.s3.amazonaws.com/libpostal_data.tar.gz -z "Mon Dec 26 09:20:47 UTC 2016" --remote-time -w %{http_code} -o /dev/null
304
```

**Comment by thatdatabaseguy** [comment]
Ok, merging.
