### ISSUE TITLE
Configurable data library directory to enable hadoop deployment

### ISSUE THREAD

**Issue by jamiehutton** [openvenues/libpostal#153]
Hi there,

We are trying to use LibPostal (+jpostal) as part of a wider data processing pipeline based in Spark running on YARN. We have got this working on our development environment by performing a lib postal install on each of the hadoop nodes and are able to parse addresses in parallel across the hadoop cluster. 

Unfortunately we have hit a bit of an issue when trying to deploy this within our customer environments because they do not allow for the install to occur on the individual nodes on the cluster.

From an installation perspective there are four components as we understand it:

1.	LibPostal Data Library (all the reference data load to the configured datadir).
2.	The libpostal C libraries which need to be on the LD_LIBRARY_PATH
3.	JPostal’s JNI C libraries which need to be on the java.library.path
4.	JPostal’s java library (jpostal.jar)

The main issue we are having is that the location of the data library / directory is hard coded into libpostal C library at the time of compile, which makes the libraries non portable.

Question:
Would it be possible to make the data library/directory configurable either as an argument in the call to the library or as an environment variable? Obviously for backward compatibility, libpostal could use the "defaults" (set at compile time) but if the relevant argument / environment variable was set, could use this.

Thanks,
Jamie

**Comment by thatdatabaseguy** [comment]
Ok, this will only be available for C/C++ and Java users as I'd prefer to keep the dynamic language bindings as simple and function-like as possible, but I've added setup methods that take datadir arguments to the public API (you'll have to pull latest from both libpostal and jpostal).

There's an updated README in jpostal, but basically the only change is instead of:

```java
AddressParser p = AddressParser.getInstance();
```

which still works, you can also call:

```java
AddressParser p = AddressParser.getInstanceDataDir("/some/path");
```

Note: when you run ```./configure --datadir=/some/data/dir``` the full datadir will be "/some/data/dir/libpostal".

**Comment by jamiehutton** [comment]
Hi Al,

Thank you so much for making the above change so quickly and apologies for the delayed response from our side - it took a little while for us to get this all tested on our environment. The good news is the datadir change seems to be working perfectly.

We have however hit one other issue which stops libpostal being compatible with execution on our clients' hadoop cluster (where we do not have control of the underlying OS for the workers running the parsing). That is the need to set LD_LIBRARY_PATH and ensure you have pre-distributed the libpostal C libraries in that location.

The  jpostal C libraries are configured via the -Djava.library.path JVM option, but it seems the dependency libpostal C libraries can't just be placed on this path - they have to be on LD_LIBRARY_PATH. Not being familiar with C I'm not sure what options there are when loading libraries. However, would it be possible for jpostal to load it's libpostal dependencies differently, to avoid using a shared library on LD_LIBRARY_PATH and perhaps in some way make it relative?

The following post mentions some options:
https://blogs.oracle.com/ali/entry/avoiding_ld_library_path_the
The first "ORIGIN" option might be a candidate here as I we think it should be possible to get YARN to distribute the libraries to the containers working directory prior to the container being started. 

We really appreciate your help. From what I can tell it does seem like the LD_LIBRARY_PATH change is the last blocker to getting massively distributed address parsing working on our hadoop cluster without performing an install / config step on each node - that would be amazing.

Thanks again - if there is anything we can do to help the libpostal project or if you have any more questions, please let me know

Jamie

**Comment by thatdatabaseguy** [comment]
Ah yes, LD_LIBRARY_PATH. ```-R``` would be one option.

[This StackOverflow thread](http://stackoverflow.com/questions/31789518/set-ld-library-path-or-java-library-path-for-yarn-hadoop2-jobs) contains another solution that might work, which is adding the following to mapred-site.xml:

```xml
<property>
<name>mapred.child.java.opts</name>
<value>-Djava.library.path=$PATH_TO_NATIVE_LIBS</value>
</property>
```

Have also seen something like this:
```scala
conf.setExecutorEnv("LD_LIBRARY_PATH", "/some/path") 
```

or if that doesn't work:
```scala
conf.setExecutorEnv("SPARK_JAVA_OPTS", "-Djava.library.path=/some/path") 
```

Re: supporting the project, there are a couple of ways, either financially through our OpenCollective (https://opencollective.com/libpostal - sponsoring a project on OpenCollective puts your company logo on our repo page, similar to sponsoring a conference or event, but it stays up for longer), by providing address/venue data sets as licensing allows, or by contributing language expertise. For more information, feel free to email me at: [first name][last name][at][gmail.com]

**Comment by jamiehutton** [comment]
Hi Al,

Thanks for the instructions above - we tried the first option you mentioned and this worked. Steps basically were:

1)	Build libpostal and jpostal as normal
2)	Put all of the libpostal and jpostal libraries into one directory (combined_libraries). Copy using cp -av to preserve links
3)	sudo yum install chrpath
4)	cd combined_libraries
5)	chrpath -r '$ORIGIN' libjpostal_parser.so.0.0.0
6)	chrpath -r '$ORIGIN' libjpostal_expander.so.0.0.0
7)	ldd files in above two steps to check can still find libpostal libraries
8)	Next remove all the links in combined_libraries by copying the target (e.g. if A -> B then make a copy of B named A)

############ Making it work in spark-shell ############

We then zipped up the directories such that we don’t have specify all the files manually on the spark-submit command line:

From ‘combined_libraries’ > tar -czf /mnt/address_parser/combined.tar.gz .

Then we can run spark with the following:

spark-shell --num-executors 3 --conf "spark.yarn.dist.archives=/mnt/address_parser/combined.tar.gz" --jars /mnt/address_parser/jpostal/build/libs/jpostal.jar --conf "spark.executor.extraLibraryPath=./combined.tar.gz" --conf "spark.driver.extraLibraryPath=./combined.tar.gz" --driver-library-path=/mnt/address_parser/combined_libraries/

############ Getting the data onto the executor nodes ############

We also had a requirement to get the data onto each executor nodes:

From ‘data dir’ > tar -czf /mnt/address_parser/libpostal_datadir.tar.gz .

spark-shell --conf "spark.yarn.dist.archives=/mnt/address_parser/combined.tar.gz,/mnt/address_parser/libpostal_datadir.tar.gz" --jars /mnt/address_parser/jpostal/build/libs/jpostal.jar --conf "spark.executor.extraLibraryPath=./combined.tar.gz" --conf "spark.driver.extraLibraryPath=./combined.tar.gz" --driver-library-path=/mnt/address_parser/combined_libraries/

When running on executors you can now use 
val parser = AddressParser.getInstanceDataDir("./libpostal_datadir.tar.gz")


This means we can now run libpostal distributed across our entire hadoop cluster without performing an install on any individual node. The main caveat here is that libpostal needs to be compiled on a node which is the same as the rest of the cluster, and the nodes themselves have to have the relevant libpostal prerequisites 

Thanks again for your help!!

Jamie

**Comment by reemak** [comment]
@jamiehutton @albarrentine 
I`m trying to run Libpostal(+jpostal) on Spark cluster on HDInsight on Azure and using Zeppelin notebook for code.
![image](https://user-images.githubusercontent.com/7968031/71852390-7209fa80-308d-11ea-84ea-e94430b25c6b.png)

Any idea how I can fix it?

**Comment by jamiehutton** [comment]
Hi Reemak,

It sounds like the jpostal jar hasnt been added to the classpath. In spark-shell / spark-submit, you do this with:
--jars /<path-to>/jpostal.jar 

I am not sure the equivalent in Zeppelin on HDInsight - i would try and get it working in spark shell first probably

Jamie

**Comment by reemak** [comment]
Hey @jamiehutton 

I`m newbie with Spark
I`m really struggling on how to do this.
Can you give detailed steps please?

**Comment by reemak** [comment]
From what I understand spark-submit needs parameters like class name, input file and output file.
In this case we dont have main class. So what class name should we use here?
I tried using classname = jpostal.AddressExpander and got the following error: 

![image](https://user-images.githubusercontent.com/7968031/72121282-72b1c380-330f-11ea-9232-3d5a8edb9e0e.png)

**Comment by avikaps** [comment]
Hello Everyone, 
I have still facing this issues, Has this been resolved earlier ? Do we have any work arounds to get rid of this issue ?

**Comment by jamiehutton** [comment]
> Hello Everyone,
> I have still facing this issues, Has this been resolved earlier ? Do we have any work arounds to get rid of this issue ?

We have this working and in production at a number of customers, so the issue has definitely been resolved. If you haven't done so already please do go through the notes above and see if you can get it working that way
