### ISSUE TITLE
Mutliple tags for v0.3.3

### ISSUE THREAD

**Issue by saveman71** [openvenues/libpostal#155]
Hello,

I believe you made a mistake with the tag [`0.3.3`](https://github.com/openvenues/libpostal/tree/0.3.3) (**not** `v0.3.3`).

This breaks `git describe --long --tags` which will return `0.3.3` instead of `v0.3.3` for some reason, and I use it in a package I'm building for my machine (Arch Linux package, I'll release it later to the public, some discussion can be found [here](https://bbs.archlinux.org/viewtopic.php?pid=1680928)).

Could you care to remove it, please?

Thanks.

**Comment by thatdatabaseguy** [comment]
Done.

**Comment by saveman71** [comment]
Thanks again!
