### ISSUE TITLE
Binaries for Windows

### ISSUE THREAD

**Issue by checkexpress** [openvenues/libpostal#158]
Hello,
I am planning to use libpostal together with my legacy code running under Windows. Is there a short term roadmap to have a Windows Binary of libpostal ? If not, can you kindly provide further instructions of how can I compile it using, for example, Mingw ?
Thanks in advance, 
Ricardo

**Comment by thatdatabaseguy** [comment]
This has been brought up several times in other issues. Libpostal works on Mac and Linux - I'm happy to accept pull requests for Windows but it's not a priority. Others have reported difficulty compiling on Windows because of the reliance of one of our modules on mmap.

**Comment by checkexpress** [comment]
Thank you for the clarification. Cheers
