### ISSUE TITLE
Centos 7 / Redhat install - headers not linking for pkgconfig 

### ISSUE THREAD

**Issue by Nexidyne** [openvenues/libpostal#166]
After fresh install, 
pkg-config --cflags libpostal
would not include libpostal

Adding the symlink:
ln -s /usr/local/lib/pkgconfig/libpostal.pc /usr/share/pkgconfig/libpostal.pc
resolved the issue.

**Comment by thatdatabaseguy** [comment]
That sounds like the /usr/local/lib version is just not on PKG_CONFIG_PATH. Would ```PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig``` resolve as well?

**Comment by thatdatabaseguy** [comment]
Has this been resolved?
