### ISSUE TITLE
LuaJIT FFI bindings to libpostal

### ISSUE THREAD

**Issue by bungle** [openvenues/libpostal#17]
Just to let you know, I created LuaJIT FFI bindings to libpostal, in case you want to link for unofficial or alternate implementations or bindings:

https://github.com/bungle/lua-resty-postal/blob/master/lib/resty/postal.lua

It works with plain LuaJIT (the resty thing here is that I just want to support especially OpenResty community).

**Comment by thatdatabaseguy** [comment]
Thanks Aapo! Sorry for the delay, I've added an unofficial bindings section to the README and listed the Lua binding.

I'll bet it's now possible to build a geocoder backed by Redis.

**Comment by bungle** [comment]
Well, as far as I know, Redis itself doesn't use LuaJIT but PUC Lua. I'm not certain does Redis allow external Lua C modules to be loaded or is it just plain Lua code. But it is interesting thing to consider. At least you may utilize this with your LuaJIT or maybe OpenResty projects :-).
