### ISSUE TITLE
Parsing and removing street markers

### ISSUE THREAD

**Issue by sxmon** [openvenues/libpostal#173]
Hi,

When parsing addresses, I noticed that people often mistake between "rue" and "avenue" or "c/" and "avenida". I would like to remove these words when parsing the address.

For instance : 

"100 main street ny"

is parsed to  : 

"road" : "main street"

And I would like to remove "street".

Thank you,

Simon

**Comment by thatdatabaseguy** [comment]
Libpostal's [dictionaries](https://github.com/openvenues/libpostal/tree/master/resources/dictionaries) are probably a decent place to start. Each language has a street_types.txt with the canonical word on the left and all of its abbreviations to the right, delimited by the pipe character "|".

Just a thought: if you're using a full-text search engine that weights by IDF, very common words like "Street" may not factor into the rankings much.

**Comment by sxmon** [comment]
Thank you, it is exactly what I was looking for.

I will work on some code and maybe post it.
