### ISSUE TITLE
Complete list of libpostals result fields

### ISSUE THREAD

**Issue by dominikkukacka** [openvenues/libpostal#174]
Is there somewhere a documentation of the complete list of libpostal fields which could be returned by the parse function?
Also, is there a test string (test address) which fills all of these fields?

**Comment by thatdatabaseguy** [comment]
List of fields is here: https://github.com/openvenues/libpostal#parser-labels. I can't think of a test string that would use all fields because they're for different kinds of queries and not every country has every admin level.

**Comment by dominikkukacka** [comment]
thank you! I overread that!
