### ISSUE TITLE
Access denied to download 2017-03-04 training data

### ISSUE THREAD

**Issue by twain47** [openvenues/libpostal#179]
Accessing:
https://libpostal.s3.amazonaws.com/training_data/2017-03-04/parser/uk_openaddresses_formatted_addresses_tagged.random.tsv.gz

Produces:
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4EDDC120287B937E</RequestId>
...

for all the files in this training set. 

Accessing files from the 2017-01-10 dataset works: https://libpostal.s3.amazonaws.com/training_data/2017-01-10/formatted_places_tagged.random.tsv
so presumably a permissions error on s3?

**Comment by thatdatabaseguy** [comment]
Hey @twain47 (thanks for Nominatim btw!) That's one of the older training sets (latest is 2017-03-04), might not have set acl=public-read on S3. Will re-upload them and gzip them while I'm at it to save people some bandwidth.

**Comment by twain47** [comment]
np, I wish I had more time to do development on it!

It is actually the latest https://libpostal.s3.amazonaws.com/training_data/2017-03-04/parser/* that I'm having trouble grabbing. The older set is working.

**Comment by thatdatabaseguy** [comment]
Oh, misread that. Ok, added acl=public-read to all the files in that bucket.

**Comment by twain47** [comment]
Excellent - many thanks.

Libpostal really is extraordinary btw. I tried it out previously but 1.0 has added so much.

**Comment by thatdatabaseguy** [comment]
Much appreciated!
