### ISSUE TITLE
Is it possible to download all the data files manually?

### ISSUE THREAD

**Issue by cottonty** [openvenues/libpostal#182]
I am living in China and because of the Great Fire Wall I failed downloading data files in make every time. I have tried since the weekend, no matter download through VPN or not it makes no difference.
I will be very grateful if there is a way to download data files manually.

**Comment by thatdatabaseguy** [comment]
Hey @cottonty, the files are hosted in the "us-east-1" AWS region (northern Virginia in the US), so downloading hundreds of megabytes from outside of the country is probably slow. It seems like many VPN services are now banned within China

According to [Amazon](https://www.amazonaws.cn/en/about-aws/china/faqs/), hosting files in the Beijing region requires having a Chinese company with an ICP license, so that's a no-go. The closest option I could find is hosting the files on the CloudFront CDN, which has [edge locations](https://aws.amazon.com/cloudfront/details/#Detailed_Description) in a few nearby places: Hong Kong, Tokyo, and Seoul. So still have to cross the GFW but the data's at least closer to mainland China.

I've set up a CloudFront distribution for the model files as of #183, so if you pull latest and keep trying to run ```make``` (or can manually run the download script with ```./src/libpostal_data download all $YOUR_DATA_DIR/libpostal```), hopefully the nearby caches will populate and the download will eventually complete.

Also, if you happen to have any sources for address data in China that we can use for libpostal, I'd love to hear about them!

**Comment by cottonty** [comment]
thank you.
but this time it stuck at here

address_expansions/
address_expansions/address_dictionary.dat
numex/
numex/numex.dat
transliteration/
transliteration/transliteration.dat
make[2]: *** [all-local] Error 7
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2


actually, could you give me all the download addresses of needed files like this
http://libpostal.s3.amazonaws.com/models/address_parser/2017-03-04/parser.tar.gz
I'm able to download this with download software
having these I can then extract them into the data directory.

**Comment by thatdatabaseguy** [comment]
Ok, so the basic data files use a simple url, and it looks like you already have them:

**base data files**: https://d1p366rbd94x8u.cloudfront.net/libpostal/data/v1/libpostal_data.tar.gz

For the models, the dates may change over time. But the urls can be obtained by checking for a file called "latest" in either of the model directories, like so:

**address_parser**
```
latest=$(curl --silent https://libpostal.s3.amazonaws.com/models/address_parser/latest)
url=https://d1p366rbd94x8u.cloudfront.net/models/address_parser/$latest/address_parser.tar.gz
```

**language classifier**:
```
latest=$(curl --silent https://libpostal.s3.amazonaws.com/models/language_classifier/latest)
url=https://d1p366rbd94x8u.cloudfront.net/models/language_classifier/$latest/language_classifier.tar.gz
```

After the tarballs have been downloaded and extracted, create the following files so libpostal's ```make``` doesn't attempt to download the data again:

```
echo $(date -u) > $YOUR_DATA_DIR/libpostal/last_updated
echo $(date -u) > $YOUR_DATA_DIR/libpostal/last_updated_parser
echo $(date -u) > $YOUR_DATA_DIR/libpostal/last_updated_language_classifier
echo "v1" > $YOUR_DATA_DIR/data_version
```

**Comment by cottonty** [comment]
thank you so much!!
it works!

**Comment by davebenvenuti** [comment]
`https://d1p366rbd94x8u.cloudfront.net/libpostal/data/v1/libpostal_data.tar.gz` now returns a 404 for me

**Comment by Lichenying99** [comment]
> Hey @cottonty, the files are hosted in the "us-east-1" AWS region (northern Virginia in the US), so downloading hundreds of megabytes from outside of the country is probably slow. It seems like many VPN services are now banned within China as well, so that might be part of it.
> 
> According to [Amazon](https://www.amazonaws.cn/en/about-aws/china/faqs/), hosting files in the Beijing region requires having a Chinese company with an ICP license, so that's a no-go. The closest option I could find is hosting the files on the CloudFront CDN, which has [edge locations](https://aws.amazon.com/cloudfront/details/#Detailed_Description) in a few nearby places: Hong Kong, Tokyo, and Seoul. So still have to cross the GFW but the data's at least closer to mainland China.
> 
> I've set up a CloudFront distribution for the model files as of #183, so if you pull latest and keep trying to run `make` (or can manually run the download script with `./src/libpostal_data download all $YOUR_DATA_DIR/libpostal`), hopefully the nearby caches will populate and the download will eventually complete.
> 
> Also, if you happen to have any sources for address data in China that we can use for libpostal, I'd love to hear about them!


hi,sorry to bother you ,and I am in China too,just tried the method referred, but it doesn't matter .I still can't  download the files ,would you pls help me?

**Comment by Abhiram007** [comment]
Hi , Could anyone post the live link for downloading all the data files ? The above links are no longer functional.
Its would be great if anyone can provide all the .dat files after the model has been trained.

**Comment by Lichenying99** [comment]
Sorry, I’m  also  looking for the data ,we can keep contact if anyone have progress

发件人: Abhiram [mailto:notifications@github.com]
发送时间: 2019年4月4日 13:54
收件人: openvenues/libpostal <libpostal@noreply.github.com>
抄送: lichenying (A) <lichenying1@huawei.com>; Comment <comment@noreply.github.com>
主题: Re: [openvenues/libpostal] Is it possible to download all the data files manually? (#182)


Hi , Could anyone post the live link for downloading all the data files ? The above links are no longer functional.
Its would be great if anyone can provide all the .dat files after the model has been trained.
