### ISSUE TITLE
Adding street type parser label

### ISSUE THREAD

**Issue by VartanBelavejian** [openvenues/libpostal#188]
So I am looking for the ability to have a separate label for street type and possibly direction rather than having it bundled with street name. Is this something that can be added without too much difficulty? I see some of these details in the data.

**Comment by thatdatabaseguy** [comment]
Unfortunately no, that's not easy. OpenStreetMap and most other data sets we use to train libpostal do not have separate fields for street type. For addresses in the US, there are fields like "tiger:name_base", "tiger:name_type", "tiger:name_direction_prefix", etc. that could possibly be used, but that wouldn't work internationally. The libpostal dictionaries do contain street types, which is probably what you're seeing, but those could only really be used to do deterministic labeling, not as ground truth for training a machine learning model.
