### ISSUE TITLE
Is it possible to use Libpostal for detecting the address from website?

### ISSUE THREAD

**Issue by JafferWilson** [openvenues/libpostal#192]
I would like to know if I input the website page using HTML or even plain text, then is it possible to extract the street, city, state, country, zip/postal code etc. from that text using the libpostal?
If there is any mechanism that could help then kindly suggest me. I would love to hear about it. Thank you in advance.

**Comment by thatdatabaseguy** [comment]
Hey @JafferWilson, wrote about this in a [previous issue](https://github.com/openvenues/libpostal/issues/22), but no, it's not possible with libpostal. I know a lot of users who are writing scrapers, etc. want this "feature", but in reality it's a very different machine learning problem (information extraction) and it would be more difficult to obtain a large, suitable training set in multiple languages.

While libpostal could certainly be very useful as input in identifying whether a given block contains an address or not, it's not trained on non-address tokens, so if you pass it a full web page, it would try to classify every word as some part of an address.

If you're scraping modern websites, I'd suggest trying lower-hanging-fruit methods like [microdata](https://schema.org/Place) first and seeing if that's sufficient. Structured data yields close to 100% accuracy vs. a machine learning/information extraction approach which might be able to extract more addresses from older websites, but will not be perfect, and may be very far from perfect. Let's say you built a system that achieved 95% precision (fraction of all addresses identified that were actually addresses). That's a fairly good result in information extraction, and if there's a human in the loop to verify that the extracted addresses were correct for each page, that might be acceptable. However, if the goal is to automatically populate an address database, it's going to contain a lot of errors. If you ran the 95% solution on 10 million webpages, which is a very small fraction of the Internet, your DB would contain 500,000 mistakes.

**Comment by JafferWilson** [comment]
@thatdatabaseguy  Thank you very much for your reply and clarification. I am glad to hear an insightful explanation regarding the issue I had and yes, I will try to have some different methods. There is no room for mistakes in my case and if I need to make corrections every time then that is a very time-consuming activity.
Thank you once again.

**Comment by Catonzio** [comment]
@JafferWilson Hello, I am trying to do a software in which one of the features is to detect addresses in a web-page. I have tried with Regex expressions, but it is not a good idea. How did you resolve your problem? I am programming with Java.
