### ISSUE TITLE
Canadian address with left-hyphenated unit/suite 

### ISSUE THREAD

**Issue by nurey** [openvenues/libpostal#197]
Are there any plans to be able to parse Canadian addresses like "#401-43 HANNA AVE" where the street number is 43 and unit number is 401?

**Comment by thatdatabaseguy** [comment]
No, sorry. Libpostal tags each token in the string with a label, and tries not to modify the user input too much. As far as our tokenizer is concerned "401-43" is one atomic token and cannot be broken down further. Also, libpostal is an international parser and that format isn't used in the same way in all countries. There's a lot of ambiguity in what a hyphen means around the world. Sometimes a hyphen means a range or house numbers, even within Canada (perhaps "401-403 HANNA AVE"). In the US, Queens addresses contain hyphens as part of the house number. In Japan the house number is composed of neighborhood-block-building. In Malaysia there's no consistent format for what the various hyphenated parts mean.

Luckily, that problem's not one that libpostal necessarily needs to solve. If you know a priori that your addresses are in Canada, it should be easy enough to use a regex on the output from libpostal to break our house_number component down in to unit and house number respectively. Libpostal's NLP-based model can handle the many other types of ambiguities in a free-form address, and the regex can be used to handle house numbers that match that specific pattern.
