### ISSUE TITLE
Doesn't appear to handle PO Box numbers.

### ISSUE THREAD

**Issue by sporkmonger** [openvenues/libpostal#21]
```
postal.parser.parse_address('PO Box 1, Seattle, WA 98103');
[ { value: 'po', component: 'house_number' },
  { value: 'box', component: 'road' },
  { value: '1', component: 'house_number' },
  { value: 'seattle', component: 'city' },
  { value: 'wa', component: 'state' },
  { value: '98103', component: 'postcode' } ]
```

**Comment by thatdatabaseguy** [comment]
Indeed. There are no PO box numbers currently in OSM, which is what we use to train the parser. Same deal with apartment/flat/suite numbers (those are represented in OSM, but scarcely so).

We're working to synthesize training data for some of these cases, as well as for other types of non-address geocoder input like "restaurants in Brooklyn." It's on the near-term roadmap and should be in an upcoming build of the address parser.

**Comment by sporkmonger** [comment]
Actually, if you're interested, I've got like 250 test cases full of really horrific edge case addresses. I just started using libpostal as a secondary information source for our own address parser, but I had to set the weighting really, really low to keep it from adversely affecting results for the cases it handles badly (like this one).

**Comment by thatdatabaseguy** [comment]
I'd be very interested in said test cases! We can either train on them directly or add to libpostal's test suite (or both).

**Comment by sporkmonger** [comment]
Let me check through and make sure there aren't any addresses that are sensitive first and I'll get back to you on that.

**Comment by thatdatabaseguy** [comment]
Of course, we do the same with our test cases.

**Comment by sporkmonger** [comment]
Can I email 'em to you?

**Comment by thatdatabaseguy** [comment]
Of course, it's the standard first name last name @ gmail.

**Comment by sporkmonger** [comment]
Sounds good. Expect a couple files in a few.

**Comment by coryfoo** [comment]
I'm very interested in the progress of PO Box and Apt/Suite parsing.  Is there a planned model update to handle these?  Do you need more training data?

**Comment by thatdatabaseguy** [comment]
There's a huge update coming out of the [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) branch soon. Shouldn't need more training data as far as PO boxes/apartments. The new training apparatus generates a variety of sub-building phrases randomly.

An early version of the trained model (does far better with place names, etc. and handles units, floors, and PO boxes in English and Spanish) can be found at: https://libpostal.s3.amazonaws.com/mapzen_sample/parser_full.tar.gz, if you want to try it out in the meantime. To use that (doesn't require switching branches or anything, it's the same model in master trained on new data), just unpack the contents of the tarball into $DATA_DIR/libpostal/address_parser where $DATA_DIR is whatever you passed in during configure, default being /usr/local/share.

**Comment by thatdatabaseguy** [comment]
P.O. Box numbers (and apartment numbers, floor numbers, etc.) are now added to the training data and supported in over 30 languages in the 1.0 release.

@sporkmonger the vast majority of the test cases you sent over work great as well. Have added some to the tests. There are a few known issues with the notion of locality vs. postal town in the UK but that mostly has to do with the fact that our templates only allow one city, so we end up picking one or the other. We'd have to either make it a different component or add multiple comma delimited cities for UK addresses. In any case, that's a separate issue.
