### ISSUE TITLE
I am seriously thinking about porting this library to a full Visual Studio environment

### ISSUE THREAD

**Issue by yumcious** [openvenues/libpostal#217]
The company I work for doesn't take too kindly to having non-MS development tools in its repertoire.  Let's not get down that religious debate.

Is a Visual Studio even possible?  **Am I nuts** to even try to want to do this?  

The alternative is to use regex.  Just thinking about this alternative makes me break out in hives.

Please advise.

**Comment by thatdatabaseguy** [comment]
Feel free to do so and send a pull request. There's no particular religion here, just priorities. Libpostal is tested on Mac and Linux, and if fairly explicit about that. Support for other OSes is welcome as long as it doesn't affect our target use cases (i.e. tests pass) and can be sufficiently abstracted so it doesn't make the code illegible.
