### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by stevenicholls99** [openvenues/libpostal#222]
I am looking for a way to leverage this library for international address parsing using .NET. I dont know C (only VB or C#). Would you be interested in helping to get this implemented as a paid project?

**Comment by thatdatabaseguy** [comment]
Libpostal is tested on Mac and Ubuntu, and it's reported to work on most other popular flavors of Linux, but that's it. One user reported getting it to compile/work on Windows with MinGW in https://github.com/BenK10/libpostal_windows, but it's not merge-able into this repo. I'm happy to accept a pull request if anyone gets a working MSVC build that can be tested via AppVeyor.

After libpostal compiles on Windows, it should be relatively easy for folks to write a .NET binding. The libpostal C API is very small and serves as a decently useful starter project for people interested in calling C functions from their preferred language.
