### ISSUE TITLE
usage of the -disable-data-download flag

### ISSUE THREAD

**Issue by missinglink** [openvenues/libpostal#224]
hey Al, I saw the `-disable-data-download` flag in https://github.com/openvenues/libpostal/blob/master/configure.ac#L80-L86.

maybe it's the double negatives getting me confused but it looks like the default behavior is `DOWNLOAD_DATA=true` and when you say `--disable-data-download=yes` (as in disabled=yes) then it's still `DOWNLOAD_DATA=true` and the inverse for the other case?

also, I'm not familiar with the syntax, can I say `--disable-data-download=1` or do I have to say `--disable-data-download=yes`?

```bash
AC_ARG_ENABLE([data-download],
              [  --disable-data-download    Disable downloading data],
              [case "${enableval}" in
                yes)  DOWNLOAD_DATA=true ;;
                no) DOWNLOAD_DATA=false ;;
                *) AC_MSG_ERROR([bad value ${enableval} for --disable-data-download]) ;;
              esac], [DOWNLOAD_DATA=true])
```

thanks!

**Comment by thatdatabaseguy** [comment]
See https://github.com/openvenues/libpostal/pull/225#issuecomment-315840721
