### ISSUE TITLE
.dat files

### ISSUE THREAD

**Issue by cjd22** [openvenues/libpostal#227]
Hi Everyone. I am building for Windows and am looking for the transliteration.dat, numex.dat and address_dictionary.dat files. Without them my program comes to a halt. I see that in Unix the files are downloaded using make. Does any one have the files in a zip or a link as to where I could obtain them. Or better still have any idea how to get them  using Windows. Any help would be appreciated. Thanks

**Comment by thatdatabaseguy** [comment]
There are 3 tarballs stored on S3/Cloudfront. The current versions are available here:

https://d1p366rbd94x8u.cloudfront.net/data/v1/data/libpostal_data.tar.gz
https://d1p366rbd94x8u.cloudfront.net/models/address_parser/2017-03-04/parser.tar.gz
https://d1p366rbd94x8u.cloudfront.net/models/language_classifier/2016-01-27/language_classifier.tar.gz

**Comment by cjd22** [comment]
Hi  thatdatabaseguy, Thanks for the response. The links you gave me

address_parser_crf.dat,
address_parser_phrases.dat,
address_parser_postal_codes.dat,
language_classifier.dat,

The first link is dead. I am looking for transliteration.dat, numex.dat and address_dictionary.dat files. These are the files that are required in libpostal_setup_datadir() function that is called from the main() function. If the files are not found the program exits. Do you have any other information as to how to get hold of the relevant files. Thanks

**Comment by thatdatabaseguy** [comment]
Sorry, corrected the first link in the comment above. That tarball libpostal_data.tar.gz gives you transliteration.dat, numex.dat and address_dictionary.dat.

**Comment by cjd22** [comment]
Hi thatdatabaseguy,

Thanks for correcting the link.
When I run the program I am getting an exception error thrown
Stack around the variable category was corrupted. 
This is when the program is reading numex.dat.
Is the numex.dat corrupted.If not do you have any ideas ?
Thanks

**Comment by thatdatabaseguy** [comment]
That sounds like a 32-bit issue related to stack-smashing (all of our tests run on 64-bit systems, so they don't catch everything). Early on, I'd corrected all the errors relating to reading 64-bit ints into 32-bit `size_t` types, but there were a couple more in numex where 64-bit ints were being read into 32-bit `enum` types, which can also lead to stack corruption.

Just merged #229, which should make libpostal fully 32-bit compatible.

Note: libpostal is only tested on Mac and Linux - if there are more issues that are Windows-specific, you'll need to solve them on your own and send a pull request with the changes as I have no Windows machines on which to test.
