### ISSUE TITLE
Address Parser not recognizing street names

### ISSUE THREAD

**Issue by cjd22** [openvenues/libpostal#230]
HI,

I'm just testing the program using the C equivalent of the Python bindings

from postal.parser import parse_address
parse_address('The Book Club 100-106 Leonard St Shoreditch London EC2A 4RH, United Kingdom')

In C

#include <stdio.h>
#include <stdlib.h>
#include <libpostal/libpostal.h>

int main(int argc, char **argv) {
    // Setup (only called once at the beginning of your program)
    if (!libpostal_setup() || !libpostal_setup_parser()) {
        exit(EXIT_FAILURE);
    }

    libpostal_address_parser_options_t options = libpostal_get_address_parser_default_options();
    libpostal_address_parser_response_t *parsed = libpostal_parse_address("781 Franklin Ave Crown Heights Brooklyn NYC NY 11216 USA", options);

    for (size_t i = 0; i < parsed->num_components; i++) {
        printf("%s: %s\n", parsed->labels[i], parsed->components[i]);
    }

    // Free parse result
    libpostal_address_parser_response_destroy(parsed);

    // Teardown (only called once at the end of your program)
    libpostal_teardown();
    libpostal_teardown_parser();
}

The program crashes with the address in the example code. But when I run the code with the address changed to 

libpostal_address_parser_response_t *parsed = libpostal_parse_address("21, Main street, Nottingham, UK", options);

it runs fine and prints the results.

Anyone have any ideas ?

**Comment by thatdatabaseguy** [comment]
Ok, this is partially on me for not having written the contributing guide yet, but crash reports need a lot more specificity:

1. Which OS are you using? Is this Windows?
2. What kind of crash is it (segfault, etc.)? What's the output?
3. Can you run it with valgrind or equivalent and paste those results?

As mentioned in #227, I'd strongly prefer pull requests related to Windows instead of issues as I have no Windows machines and won't be able to replicate issues. libpostal is tested on Mac and Ubuntu.

**Comment by cjd22** [comment]
Hi,
Yes it is Windows. I thought using the C equivalent of the python bindings it might work.

I get Exception thrown read access violation.
str pointer was null in function
inline void char array_append(char_array *array, char *str);

it seems to originate from calling the function
//word e.g. if the current word is unknown and the next word is "street"
feature_array_add(features, 2, "next word", next_word);

in address_parser.c called from address_parser_features function

Thanks

**Comment by thatdatabaseguy** [comment]
Read access violation is an MSVC thing. Step through the code with a debugger and check the values, but it's possible that the function `word_or_phrase_at_index` is implemented in a way that's not Windows compatible.

Beginning to sound like a broken record but the example code has only been tested on Mac/Linux with relatively modern versions of C99-compliant compilers like gcc and clang. There are no guarantees that libpostal works or even compiles on Windows. The policy is: I'm willing to remove obstacles for Windows users when I'm made aware of them, or better yet, I get a pull request, but I'm not willing to remotely debug Windows issues. This is effectively uncharted territory, and a forum like StackOverflow where Windows developers can answer may be the best option.
