### ISSUE TITLE
language classifier

### ISSUE THREAD

**Issue by cjd22** [openvenues/libpostal#232]
Hi,

I was just wondering if anyone could post a link or tell me how to get the language_classifier.dat file as I trying to exapnd address via libpostal_expand_address() function and it needs the language_classifier.dat file

Thanks

**Comment by thatdatabaseguy** [comment]
Current version is here: https://d1p366rbd94x8u.cloudfront.net/models/language_classifier/2016-01-27/language_classifier.tar.gz
