### ISSUE TITLE
Hyde Park (suburb of Johannesburg, South Africa)

### ISSUE THREAD

**Issue by coachwei** [openvenues/libpostal#235]
Input:

`Hyde Park, Joannesburg, Gauteng, South Africa`

Output:
`
house: Hyde Park, 
city: Joannesburg,
state: Gauteng,
country: south africa
`
It should be:
`
suburb: Hyde Park, 
city: Joannesburg,
state: Gauteng,
country: south africa
`

**Comment by thatdatabaseguy** [comment]
Hyde Park is also the name of a [shopping center](https://www.openstreetmap.org/way/53531986), and that is the first result returned in OSM. When an entry is not contained within a city polygon (in the case of Johannesburg, there is no city boundary polygon, only the [City of Johannesburg Metropolitan Municipality](https://www.openstreetmap.org/relation/594508) which is classified as a `state_district`), so cities are assigned by closest point. In the case of Hyde Park the suburb, its closest city is Randburg, whereas for the shopping center the closest city actually is Johannesburg. Our method is very similar to what OSM's Nominatim does when displaying results.

Parse is not invalid, won't fix.
