### ISSUE TITLE
South Africa Address Parsing (unit, house_number, road, house confusion)

### ISSUE THREAD

**Issue by coachwei** [openvenues/libpostal#237]
Here is the input:
`308 SOHO on Strand, 128 Strand Street, Cape Town, W Cape, 8005, South Africa
`
Current parsing result:

```
                house_number:308
                road:soho on strand
                house_number:128
                road:strand street
                city:cape town w cape
                postcode:8005
                country:south africa
```

It should be:

```
                unit:308
                house: soho on strand
                house_number:128
                road: strand street
                city:cape town
                state: w cape
                postcode:8005
                country:south africa
```

**Comment by thatdatabaseguy** [comment]
Won't fix.

- this works: ```SOHO on Strand, 128 Strand Street, Cape Town, Western Cape, 8005, South Africa```
- so does this: ```Unit 308 SOHO on Strand, 128 Strand Street, Cape Town, Western Cape, 8005, South Africa```

Those forms are more standard and we're not going to generate naked unit numbers like "308" to the training data as they're difficult to disambiguate from house numbers and humans don't commonly write addresses that way.

Will add the abbreviation "W" for "Western" as opposed to just "West" which will allow the parser to get "W Cape".
