### ISSUE TITLE
Order of expand_address

### ISSUE THREAD

**Issue by RichardSieg** [openvenues/libpostal#240]
Hi! You've mentioned that: 
At the moment, libpostal does not attempt to resolve ambiguities in addresses [...] Future iterations of expand_address will probably use OpenStreetMap (where abbreviation is discouraged) to build classifiers for ambiguous expansions, and include an option for outputs to be ranked by likelihood. This should help folks who need a “single best” expansion e.g. when displaying the results on a map.

We'd like to have a single best expansion. Is this feature available in the current github version, i.e., is the first entry of expand_address the best guess?

Thank you,

Richard

**Comment by thatdatabaseguy** [comment]
@RichardSieg no, the output of expand_address is meant to be treated as an unordered set, and there are no plans to order the results at this time. Parsing and deduping are the primary use cases for libpostal and in deduping, ordered results are not as necessary.
