### ISSUE TITLE
Was the ß -> ss normalization removed?

### ISSUE THREAD

**Issue by mkaranta** [openvenues/libpostal#241]
I know the normalization was removed from `parse()` but it's a useful one to have in `expand()`. I'm not sure if this is a bug or intended.

Example:
```
libpostal$ ./src/libpostal Dratelnstraße
dratelnstraße
drateln straße
```

**Comment by thatdatabaseguy** [comment]
No it wasn't removed (any other string with ß normalizes to ss). When abbreviations are normalized to their canonical form, and the canonical is something like straße, the canonical form itself also needs to be normalized. What changed in 1.0 was that ß=>ss is no longer part of the standard UTF-8 normalizations (it was actually part of lowercasing through Unicode [case folding](http://www.unicode.org/Public/10.0.0/ucd/CaseFolding.txt) previously, whereas now we use a true lowercasing method that doesn't strip information), so the canonical strings need to instead be Latin-ASCII or Latin-ASCII-Simple transliterated depending on the options.

Just pushed a change which fixes the issue. Pull latest and that input will normalize to:
```
dratelnstrasse
drateln strasse
```

That's with the default options anyway. It's also possible to turn this off with latin_ascii=False (available in some form in the various language bindings, the command-line client just uses the default options).

**Comment by mkaranta** [comment]
Cool, thanks @thatdatabaseguy !
