### ISSUE TITLE
Unable to install libpostal-1.1

### ISSUE THREAD

**Issue by unni1988** [openvenues/libpostal#242]
Hi All,

I am trying to install libpostal-1.1 in one of our servers with RHEL 6.8. But we are getting error while making the same. Please find the below error.
Note : The server is not connected to internet
libpostal data file up to date
make[2]: *** [all-local] Error 7
make[2]: Leaving directory `/var/home/unnikms/libpostal-1.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/home/unnikms/libpostal-1.1'
make: *** [all] Error 2

**Comment by unni1988** [comment]
Thanks in advance

**Comment by thatdatabaseguy** [comment]
Libpostal 1.1 is a development branch and is not generally available yet. I will merge it into master with a pull request when it is finished.

**Comment by thatdatabaseguy** [comment]
Also the server has to be connected to the Internet whether the data file is up-to-date or not (it still uses Internet to check whether the file is current with what's on the server).
