### ISSUE TITLE
C# bindings for libpostal

### ISSUE THREAD

**Issue by mapo80** [openvenues/libpostal#248]
I've created a C# bindings for libpostal but I don't know how to access to components and labels. Now they return sbyte**:

```
        public sbyte** Components
        {
            get
            {
                return (sbyte**) ((global::LibPostalNet.LibpostalAddressParserResponse.__Internal*) __Instance)->components;
            }

            set
            {
                ((global::LibPostalNet.LibpostalAddressParserResponse.__Internal*) __Instance)->components = (global::System.IntPtr) value;
            }
        }

        public sbyte** Labels
        {
            get
            {
                return (sbyte**) ((global::LibPostalNet.LibpostalAddressParserResponse.__Internal*) __Instance)->labels;
            }

            set
            {
                ((global::LibPostalNet.LibpostalAddressParserResponse.__Internal*) __Instance)->labels = (global::System.IntPtr) value;
            }
        }
```

Repository is here: https://github.com/mapo80/LibPostalNet

How to solve?

**Comment by thatdatabaseguy** [comment]
Not a C# user but in the C API, the struct is defined as follows:

```c
typedef struct libpostal_address_parser_response {
    size_t num_components;
    char **components;
    char **labels;
} libpostal_address_parser_response_t;
```

where both `response->components` and `response->labels` are arrays of pointers to C strings (NUL-terminated `char *`) with the same length `response->num_components`.

Here's an example of what the struct members would look like using Python:

```python
labels = ["house_number", "road", "road"]
components = ["123", "main", "street"]
num_components = 3
```

In the other bindings, we usually convert the C response to an array/list of (label, component) pairs, or a dictionary/hashmap, converting the C strings to whatever the string/unicode type is in the target language.

**Comment by mapo80** [comment]
Thanks for your answer. I've solved errors and I've committed fixes.
Here you can find C# bindings libpostal library: https://github.com/mapo80/LibPostalNet
