### ISSUE TITLE
Error during run of libpostal and libpostal rest. 

### ISSUE THREAD

**Issue by aiacovella** [openvenues/libpostal#249]
I'm seeing this error repeatedly in the console:

libpostal_1        | ERR   self->viterbi->n == 0
libpostal_1        |    at crf_tagger_predict (crf.c:127) errno: None

I'm running off of a build from the master branch on Ubunto 16.04

**Comment by thatdatabaseguy** [comment]
Sorry, that's not really an error and shouldn't be treated as one. It was originally added to make sure there weren't issues with zero-length sequences while training the model, but in practice it can come up at runtime if you're passing a lot of empty strings or strings that are simply whitespace.

Removed the message in master, pull latest to pick up the changes and recompile.
