### ISSUE TITLE
Possible version issue with libpostal-rest/Go bindings

### ISSUE THREAD

**Issue by aiacovella** [openvenues/libpostal#251]
"BANK OF ENGLAND MTG, #5 STATEHOUSE PLAZA STE 500, LITTLE ROCK, AR 72201"

parses as:

[
    {
        "label": "house",
        "value": "bank of england mtg # 5 statehouse plaza"
    },
    {
        "label": "house_number",
        "value": "ste 500"
    },
    {
        "label": "city",
        "value": "little rock"
    },
    {
        "label": "state",
        "value": "ar"
    },
    {
        "label": "postcode",
        "value": "72201"
    }
]

I believe that STE should be interpreted to be SUITE and #5 should be interpreted to be house number.

In this variation
"BANK OF ENGLAND MTG, 5 STATEHOUSE PLAZA STE 500, LITTLE ROCK, AR 72201"

 where the # is removed on front of the 5 the result is:
[
    {
        "label": "house",
        "value": "bank of england"
    },
    {
        "label": "road",
        "value": "mtg"
    },
    {
        "label": "house_number",
        "value": "5"
    },
    {
        "label": "house",
        "value": "statehouse"
    },
    {
        "label": "road",
        "value": "plaza ste 500"
    },
    {
        "label": "city",
        "value": "little rock"
    },
    {
        "label": "state",
        "value": "ar"
    },
    {
        "label": "postcode",
        "value": "72201"
    }
]

"MTG" is part of the company name but is interpreted to be road. The "5" was correctly interpreted as the house number and "plaza ste 500" was interpreted as road but probably the same issue because of the "STE".

**Comment by thatdatabaseguy** [comment]
It seems like that's an outdated version of libpostal. Have you upgraded to v1.0?

The 1.0 parser produces the following for that address:

```
> BANK OF ENGLAND MTG, #5 STATEHOUSE PLAZA STE 500, LITTLE ROCK, AR 72201

Result:

{
  "house": "bank of england mtg #5 statehouse plaza",
  "unit": "ste 500",
  "city": "little rock",
  "state": "ar",
  "postcode": "72201"
}
```

The upcoming release of v1.1 might improve on that slightly as we're producing more addresses that can have venue, building, and subdivision names (all tagged `house` but in different parts of the address), so it might be more confident in a house->house_number->house transition.

Haven't seen the company suffix "Mtg" before, which appears to stand for "Mortgage", but happy to add it to our dictionaries.

**Comment by aiacovella** [comment]
I'm pretty sure my build is checking out from the latest commit master but I can try the 1.0 tag.

**Comment by thatdatabaseguy** [comment]
Not a tag issue. I checked out the latest commit in master for that test. Is it an upgrade from 0.3 and is it pointing to the right datadir? Might try a fresh install.

**Comment by aiacovella** [comment]
This is a docker image that is being built so the recreates from scratch. Is there some place I should be telling it where to pull the data down from? I was under the impression that the build pulls the latest data.

**Comment by thatdatabaseguy** [comment]
Yes, master will pull the latest data. Where does the Docker image come from and what does it check out? Is it using a fork or something?

**Comment by aiacovella** [comment]
Not that I can see, here's the docker [file](https://gist.github.com/aiacovella/af1fa0587d7cf775cdacfe2f4c35ed2c)

**Comment by thatdatabaseguy** [comment]
Ok. So it looks like there's an argument called COMMIT: https://gist.github.com/aiacovella/af1fa0587d7cf775cdacfe2f4c35ed2c#file-gistfile1-txt-L2-L3. Check that it's not being set to anything on the command-line.

Also maybe try to replicate this in an interactive container and work backward from there. I just did a fresh checkout/bootstrap/configure/make on Ubuntu and couldn't replicate the issue, so it's got to be something to do with the container/environment. Try the CLI parser as well (`./src/address_parser`) to see if maybe it's some issue with the Go binding installation.

**Comment by aiacovella** [comment]
I removed the argument from the docker file, removed all my images then rebuilt and it looks like it is ok now. Thanks for the help.
