### ISSUE TITLE
R language binding

### ISSUE THREAD

**Issue by mbannert** [openvenues/libpostal#26]
Great library. I'd love to see a binding for #rstats ... R has nice database connectivity already, guess libpostal and R would work quite well together. There's a cpp and c interface already. I'd be willing to help out on the R part here (i.e. building an R package), still I need a little kick start on the C part. Also I am not sure about the licensing how you would package stuff. Technically c code can be part of an R package, but I don't know how much of the code here should be included in an R package. (R is GPL basically)

**Comment by LluisRamon** [comment]
An R binding would be great!

**Comment by Datactuariat** [comment]
For a quick workaround _(libpostal wrap up using the R "system" function)_, see : https://github.com/Datactuariat/Rpostal

**Comment by thatdatabaseguy** [comment]
Hello all - sorry for the delay. Oliver Keyes has been working on the C/C++ binding in a private repo and just open sourced it here: https://github.com/ironholds/poster. Should be on CRAN shortly.

There may be some changes for the next version of libpostal (I'm adding a few new parser fields for sub-building information, etc. which would change the DataFrame size) but will bump the .so version on both libpostal and the binding when that's ready.

Also re: database, Paul Ramsey (author of PostGIS) recently wrote a Postgres extension: https://github.com/pramsey/pgsql-postal.

**Comment by LluisRamon** [comment]
Great news!!

Thanks
