### ISSUE TITLE
UK London address wrongly recognized

### ISSUE THREAD

**Issue by Aknilam** [openvenues/libpostal#266]
In my case: `wren house 43, halton garden` was not recognized properly - it was parsed as a house only. I read a suggestion to split by comma (https://github.com/openvenues/libpostal/issues/265#issuecomment-339163986), but it didn't help, because "halton garden" was recognized as a house instead of a road.

I tried to append request with London and GB, but it wasn't a solution too.

The expected result is:
`
[
	{
		"label": "house",
		"value": "wren house"
	},
	{
		"label": "house_number",
		"value": "43"
	},
	{
		"label": "road",
		"value": "halton garden"
	}
]
`

**Comment by albarrentine** [comment]
As far as the road name, "Halton Garden" looks like it's a misspelling, as that road does not exist in OSM. Googling the address, it looks like it is at "43 Hatton Garden" instead. Note: libpostal can handle misspelled words in street names (it won't correct them but it will parse them, automatic spelling correction is out of scope for this project), but the word "Garden" in particular is ambiguous and is often part of a venues/house name e.g. "Community Garden", "Botanic Garden", etc. so the parser has to learn the specific cases like "Hatton Garden" where it's part of the street. With the corrected street name, libpostal gets that parse entirely correct:

```
> wren house 43, hatton garden

Result:

{
  "house": "wren house",
  "house_number": "43",
  "road": "hatton garden"
}
```

Incidentally there is also a "Halton Gardens" with an "s" in Scotland which occurs in our training set, and even though the Wren House address doesn't exist there, libpostal also gets the parse correct using that street name:

```
> wren house 43, halton gardens

Result:

{
  "house": "wren house",
  "house_number": "43",
  "road": "halton gardens"
}
```

Correcting that in any automatic way would require keeping an index of valid street names (which is too expensive memory-wise and would hurt performance in parts of the world that do not have roads fully mapped/tagged in OSM).
