### ISSUE TITLE
can't install it via pip

### ISSUE THREAD

**Issue by ImCarrot** [openvenues/libpostal#273]
C:\WINDOWS\system32>pip install postal
Collecting postal
  Using cached postal-1.0.tar.gz
Requirement already satisfied: six in c:\program files\python36\lib\site-packages (from postal)
Installing collected packages: postal
  Running setup.py install for postal ... error
    Complete output from command "c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\adity\\AppData\\Local\\Temp\\pip-build-57avx9fs\\postal\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\adity\AppData\Local\Temp\pip-15_2rjel-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\postal
    copying postal\expand.py -> build\lib.win-amd64-3.6\postal
    copying postal\parser.py -> build\lib.win-amd64-3.6\postal
    copying postal\__init__.py -> build\lib.win-amd64-3.6\postal
    creating build\lib.win-amd64-3.6\postal\tests
    copying postal\tests\test_expand.py -> build\lib.win-amd64-3.6\postal\tests
    copying postal\tests\test_parser.py -> build\lib.win-amd64-3.6\postal\tests
    copying postal\tests\__init__.py -> build\lib.win-amd64-3.6\postal\tests
    creating build\lib.win-amd64-3.6\postal\utils
    copying postal\utils\encoding.py -> build\lib.win-amd64-3.6\postal\utils
    copying postal\utils\enum.py -> build\lib.win-amd64-3.6\postal\utils
    copying postal\utils\omitted.py -> build\lib.win-amd64-3.6\postal\utils
    copying postal\utils\__init__.py -> build\lib.win-amd64-3.6\postal\utils
    running build_ext
    building 'postal._expand' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\postal
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/local/include "-Ic:\program files\python36\include" "-Ic:\program files\python36\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" /Tcpostal/pyexpand.c /Fobuild\temp.win-amd64-3.6\Release\postal/pyexpand.obj -std=c99 -Wno-unused-function
    cl : Command line error D8021 : invalid numeric argument '/Wno-unused-function'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command ""c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\adity\\AppData\\Local\\Temp\\pip-build-57avx9fs\\postal\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\adity\AppData\Local\Temp\pip-15_2rjel-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\adity\AppData\Local\Temp\pip-build-57avx9fs\postal\

**Comment by albarrentine** [comment]
This involves the Python binding. Closing in favor of the issue on that repo: https://github.com/openvenues/pypostal/issues/23
