### ISSUE TITLE
Make Fail

### ISSUE THREAD

**Issue by iBala** [openvenues/libpostal#276]
I am seeing the following error. Tried the existing forums but unable to fix the issue. Any help appreciated.
System: MacOs Sierra
----snippet----
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    ./.libs/libscanner.a(libscanner_la-scanner.o)
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    ./.libs/libscanner.a(libscanner_la-scanner.o)
ld: 87 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libpostal.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by iBala** [comment]
This has been fixed. Duplicate variables declared under src/klib/drand48.h
_rand48_add
_rand48_mult
_rand48_seed

**Comment by AeroXuk** [comment]
I've added a pull request that I hope will resolve this #278.

**Comment by albarrentine** [comment]
Fixed with #279
