### ISSUE TITLE
Gives me error while running make command

### ISSUE THREAD

**Issue by ShwetaShaw** [openvenues/libpostal#277]
Shwetas-MacBook-Pro:libpostal shwetashaw$ make
make  all-recursive
make[1]: Entering directory '/Users/shwetashaw/Desktop/libpostal'
Making all in src
make[2]: Entering directory '/Users/shwetashaw/Desktop/libpostal/src'
/bin/sh ../libtool  --tag=CC   --mode=link gcc -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR='"/Users/shwetashaw/Desktop/Dir/libpostal"' -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O2 -D LIBPOSTAL_EXPORTS  -version-info 1:0:0 -no-undefined -L/usr/local/lib -o libpostal.la -rpath /usr/local/lib libpostal_la-strndup.lo libpostal_la-libpostal.lo libpostal_la-address_dictionary.lo libpostal_la-transliterate.lo libpostal_la-tokens.lo libpostal_la-trie.lo libpostal_la-trie_search.lo libpostal_la-trie_utils.lo libpostal_la-string_utils.lo libpostal_la-file_utils.lo utf8proc/libpostal_la-utf8proc.lo cmp/libpostal_la-cmp.lo libpostal_la-normalize.lo libpostal_la-numex.lo libpostal_la-features.lo libpostal_la-unicode_scripts.lo libpostal_la-address_parser.lo libpostal_la-address_parser_io.lo libpostal_la-averaged_perceptron.lo libpostal_la-crf.lo libpostal_la-crf_context.lo libpostal_la-sparse_matrix.lo libpostal_la-averaged_perceptron_tagger.lo libpostal_la-graph.lo libpostal_la-graph_builder.lo libpostal_la-language_classifier.lo libpostal_la-language_features.lo libpostal_la-logistic_regression.lo libpostal_la-logistic.lo libpostal_la-minibatch.lo libpostal_la-float_utils.lo libpostal_la-ngrams.lo libscanner.la  
libtool: link: gcc -dynamiclib  -o .libs/libpostal.1.dylib  .libs/libpostal_la-strndup.o .libs/libpostal_la-libpostal.o .libs/libpostal_la-address_dictionary.o .libs/libpostal_la-transliterate.o .libs/libpostal_la-tokens.o .libs/libpostal_la-trie.o .libs/libpostal_la-trie_search.o .libs/libpostal_la-trie_utils.o .libs/libpostal_la-string_utils.o .libs/libpostal_la-file_utils.o utf8proc/.libs/libpostal_la-utf8proc.o cmp/.libs/libpostal_la-cmp.o .libs/libpostal_la-normalize.o .libs/libpostal_la-numex.o .libs/libpostal_la-features.o .libs/libpostal_la-unicode_scripts.o .libs/libpostal_la-address_parser.o .libs/libpostal_la-address_parser_io.o .libs/libpostal_la-averaged_perceptron.o .libs/libpostal_la-crf.o .libs/libpostal_la-crf_context.o .libs/libpostal_la-sparse_matrix.o .libs/libpostal_la-averaged_perceptron_tagger.o .libs/libpostal_la-graph.o .libs/libpostal_la-graph_builder.o .libs/libpostal_la-language_classifier.o .libs/libpostal_la-language_features.o .libs/libpostal_la-logistic_regression.o .libs/libpostal_la-logistic.o .libs/libpostal_la-minibatch.o .libs/libpostal_la-float_utils.o .libs/libpostal_la-ngrams.o   -Wl,-force_load,./.libs/libscanner.a  -L/usr/local/lib  -g -mfpmath=sse -msse2 -g -O2 -O2   -install_name  /usr/local/lib/libpostal.1.dylib -compatibility_version 2 -current_version 2.0 -Wl,-single_module
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-address_dictionary.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-address_dictionary.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-address_dictionary.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-transliterate.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-transliterate.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-transliterate.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-tokens.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-tokens.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-tokens.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-trie.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-trie.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-trie.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-trie_search.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-trie_search.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-trie_search.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-trie_utils.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-trie_utils.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-trie_utils.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-string_utils.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-string_utils.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-string_utils.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-file_utils.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-file_utils.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-file_utils.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-normalize.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-normalize.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-normalize.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-numex.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-numex.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-numex.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-features.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-features.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-features.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-unicode_scripts.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-unicode_scripts.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-unicode_scripts.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-address_parser.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-address_parser.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-address_parser.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-address_parser_io.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-address_parser_io.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-address_parser_io.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-averaged_perceptron.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-averaged_perceptron.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-averaged_perceptron.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-crf.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-crf.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-crf.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-crf_context.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-crf_context.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-crf_context.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-sparse_matrix.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-sparse_matrix.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-sparse_matrix.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-averaged_perceptron_tagger.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-averaged_perceptron_tagger.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-averaged_perceptron_tagger.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-graph.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-graph.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-graph.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-graph_builder.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-graph_builder.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-graph_builder.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-language_classifier.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-language_classifier.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-language_classifier.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-language_features.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-language_features.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-language_features.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-logistic_regression.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-logistic_regression.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-logistic_regression.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-logistic.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-logistic.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-logistic.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-minibatch.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-minibatch.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-minibatch.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-ngrams.o
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-ngrams.o
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    .libs/libpostal_la-ngrams.o
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    ./.libs/libscanner.a(libscanner_la-drand48.o)
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    ./.libs/libscanner.a(libscanner_la-drand48.o)
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    ./.libs/libscanner.a(libscanner_la-drand48.o)
duplicate symbol __rand48_mult in:
    .libs/libpostal_la-libpostal.o
    ./.libs/libscanner.a(libscanner_la-scanner.o)
duplicate symbol __rand48_seed in:
    .libs/libpostal_la-libpostal.o
    ./.libs/libscanner.a(libscanner_la-scanner.o)
duplicate symbol __rand48_add in:
    .libs/libpostal_la-libpostal.o
    ./.libs/libscanner.a(libscanner_la-scanner.o)
ld: 87 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:774: recipe for target 'libpostal.la' failed
make[2]: *** [libpostal.la] Error 1
make[2]: Leaving directory '/Users/shwetashaw/Desktop/libpostal/src'
Makefile:453: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/Users/shwetashaw/Desktop/libpostal'
Makefile:362: recipe for target 'all' failed
make: *** [all] Error 2
Shwetas-MacBook-Pro:libpostal shwetashaw$

**Comment by AeroXuk** [comment]
I've added a pull request that I hope will resolve this #278.

**Comment by ShwetaShaw** [comment]
When will i get the latest update ? Is there any way i can fix it now and use it?

**Comment by albarrentine** [comment]
Give it a few minutes for the build in #279 to complete, will merge to master as soon as it's done.

**Comment by ShwetaShaw** [comment]
Thanks a lot...Will be of great help if you update me once done. 
I will then pull the latest code and will try and update you as well

**Comment by albarrentine** [comment]
@ShwetaShaw merged! Should be working on Mac now after re-running `bootstrap.sh`/`configure`/`make`.

**Comment by ShwetaShaw** [comment]
I directly did make and it started downloading for me...Downloading still in progress

**Comment by ShwetaShaw** [comment]
Downloaded successful...Thanks 👍
