### ISSUE TITLE
32-bit Build for Windows

### ISSUE THREAD

**Issue by AeroXuk** [openvenues/libpostal#281]
I've started making a branch for this on my fork but I have a few question for @albarrentine.

Does libpostal use unsigned types for all pointer addresses?

Just doing a standard 32-bit build on windows results in the following error being thrown when trying to load the models:
```
ERR   Error loading address parser module, dir=(null)
   at libpostal_setup_parser_datadir (libpostal.c:1156) errno: Not enough space
```

This is due to Windows only allowing around a 2GB address space by default (roughly half of which is taken by the system), compiling the binaries with the `/LARGEADDRESSAWARE` flag allows a 4GB (unsigned) address space (of which about 3GB is program usable) but all memory allocations and operations must be with unsigned types.

**Comment by albarrentine** [comment]
Users have reported getting libpostal to work on 32-bit Linux, pretty sure we're 32-bit safe although our Travis CI is 64-bit only.

The address parser model takes up 1.8GB of memory (and that will most likely increase over time as the underlying data sets grow), so would definitely need `/LARGEADDRESSAWARE`. 
Most if not all of our memory allocations use `sizeof`, which returns a `size_t`, so everything should be unsigned.

**Comment by AeroXuk** [comment]
Ok, I've got AppVeyor building a 32-bit version and setting the `/LARGEADDRESSAWARE` flag within the binary successfully. If we're confident in using unsigned types I'll add a Pull request.

**Comment by michaelkolber** [comment]
I'm encountering the same error as above, even when using the AppVeyor artifacts. Any idea why?

```
ERR   Error loading address parser module, dir=(null)
 at libpostal_setup_parser_datadir (libpostal.c:410) errno:Not enough space
```
