### ISSUE TITLE
Installation error on RedHat 7.3

### ISSUE THREAD

**Issue by S-Saran** [openvenues/libpostal#287]
I'm working on Red Hat EL 7.3, trying to install libpostal.
when I run the `bootstrap.sh`, I get:

> libtoolize: putting auxiliary files in '.'.
> libtoolize: copying file './ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
> libtoolize: copying file 'm4/libtool.m4'
> libtoolize: copying file 'm4/ltoptions.m4'
> libtoolize: copying file 'm4/ltsugar.m4'
> libtoolize: copying file 'm4/ltversion.m4'
> libtoolize: copying file 'm4/lt~obsolete.m4'
> libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
> configure.ac:12: installing './missing'
> src/Makefile.am: installing './depcomp'

then I run `configure` and then I get the following error when I run `make`: 

> libpostal data file up to date
> make[1]: *** [all-local] Error 7
> make[1]: Leaving directory `[my_dir]/libpostal/src'
> make: *** [install-recursive] Error 1
> 
my package versions:
autoconf: 2.69 
automake: 1.13
libtool: 2.4.2 
pkgconfig: 0.27 

(when I do `yum --showduplicates list`, there is no pkgconfig 0.29 or automake 1.15)

Any idea what's going wrong ?

**Comment by albarrentine** [comment]
Multiple users have reported getting it to work on RedHat, though our tests only run on Ubuntu. What was the full `configure` command? Did you specify `--datadir`?

Also, can you post the full `make` output? The last 4 lines don't tell the whole story. Usually the error occurs further up.

**Comment by S-Saran** [comment]
I have specified the --datadir. Please see the output in the file attached. 
[libpostal_installation_output.txt](https://github.com/openvenues/libpostal/files/1562352/libpostal_installation_output.txt)

**Comment by albarrentine** [comment]
That output file doesn't show the error you mentioned above, and looks like a successful install. It might have had to do with downloading the data files (if there was no Internet or something during the first run).

**Comment by S-Saran** [comment]
yes, sorry. It doesn't write the error lines in the output file, it just prints them in the terminal:

> make[2]: *** [all-local] Error 7
> make[1]: *** [all-recursive] Error 1
> make: *** [all] Error 2

I tried downloading the package and installing multiple times, and the issue persists in each try. So I think that is not the issue. could it be related to cblas.h that is not checked in ./configure stage ?

**Comment by albarrentine** [comment]
Shouldn't be that - `cblas` is optional. There are conditional checks in the headers for it, and fallback methods if it's not present.

So, I think that file might be only stdout and the errors are going to stderr. Can you post stderr instead or redirect stderr to stdout?

**Comment by S-Saran** [comment]
Please see the script of terminal. I think it's the same as before. 
The only thing is that I cannot clone the repo on my server, I use the zip file, which shouldn't make a difference. Could it be any permission or directory-path issues? 
[script_install_libpostal.txt](https://github.com/openvenues/libpostal/files/1625737/script_install_libpostal.txt)

**Comment by albarrentine** [comment]
That seems like there was an error while trying to run the data download script.

Can you run `./src/libpostal_data download all /project07/data07/libpostal`?

If it's returning error code 7 (from `curl`) that would be CURLE_COULDNT_CONNECT, so maybe the machine can't connect to the Internet or there's a firewall in place.

**Comment by S-Saran** [comment]
Thanks. As you said there was a firewall blocking curl, so I specified the proxy in .curlrc and now the error 7 is resolved. 
But I still get error 2. Any ideas why is that happening?
I nevertheless tried `make install` and the `./address_parser` and I get: 

> Loading models...
> ERR   Error loading transliteration module, dir=(null)
>    at libpostal_setup_datadir (libpostal.c:266) errno: No such file or directory

Is it trying to connect to AWS-S3 or download anything from other URLs ?

**Comment by albarrentine** [comment]
Hm, seems like something didn't download correctly. Try deleting the datadir and running `make` again. If that doesn't work, try a fresh install now that the firewall is unblocked.

**Comment by S-Saran** [comment]
No luck. last few lines of `make` :

> Checking for new libpostal data file...
> libpostal data file up to date
> make[2]: *** [all-local] Error 56
> make[2]: *** Waiting for unfinished jobs....
> mv -f .deps/near_dupe_test-string_utils.Tpo .deps/near_dupe_test-string_utils.Po
> libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I.. -I/usr/local/include -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR=\"/project09/libpostal/lib_datadir/libpostal\" -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O2 -D LIBPOSTAL_EXPORTS -MT utf8proc/libpostal_la-utf8proc.lo -MD -MP -MF utf8proc/.deps/libpostal_la-utf8proc.Tpo -c utf8proc/utf8proc.c  -fPIC -DPIC -o utf8proc/.libs/libpostal_la-utf8proc.o
> libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I.. -I/usr/local/include -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR=\"/project09/libpostal/lib_datadir/libpostal\" -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O2 -D LIBPOSTAL_EXPORTS -MT utf8proc/libpostal_la-utf8proc.lo -MD -MP -MF utf8proc/.deps/libpostal_la-utf8proc.Tpo -c utf8proc/utf8proc.c -o utf8proc/libpostal_la-utf8proc.o >/dev/null 2>&1
> mv -f utf8proc/.deps/libpostal_la-utf8proc.Tpo utf8proc/.deps/libpostal_la-utf8proc.Plo
> libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I.. -I/usr/local/include -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR=\"/project09/libpostal/lib_datadir/libpostal\" -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O0 -D LIBPOSTAL_EXPORTS -MT libscanner_la-scanner.lo -MD -MP -MF .deps/libscanner_la-scanner.Tpo -c scanner.c -o libscanner_la-scanner.o >/dev/null 2>&1
> mv -f .deps/libscanner_la-scanner.Tpo .deps/libscanner_la-scanner.Plo
> make[2]: Leaving directory `/project09/libpostal/src'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory `/project09/libpostal'
> make: *** [all] Error 2

I'm on a corporate server, I've to specify each external URL I want to access from the server. Is it trying to download anything from any other host? S3?

**Comment by albarrentine** [comment]
Ah, yes, so the [data download script](https://github.com/openvenues/libpostal/blob/master/src/libpostal_data) (bash) downloads a couple of files from S3/Cloudfront. We're moving the releases to Github soon (assuming cloning this repo is possible on those servers, that might be better, right?), so the URLs may change, but here are the details for the current ones.

There are currently three tarballs that need to be downloaded at three different URLs:

**1. Base data files**: https://d1p366rbd94x8u.cloudfront.net/libpostal/data/v1/libpostal_data.tar.gz

For the models, the dates may change over time. But the urls can be obtained by checking for a file called "latest" in either of the model directories, like so:

**2. Address parser**
```
latest=$(curl --silent https://libpostal.s3.amazonaws.com/models/address_parser/latest)
url=https://d1p366rbd94x8u.cloudfront.net/models/address_parser/$latest/address_parser.tar.gz
```

**3. Language classifier**:
```
latest=$(curl --silent https://libpostal.s3.amazonaws.com/models/language_classifier/latest)
url=https://d1p366rbd94x8u.cloudfront.net/models/language_classifier/$latest/language_classifier.tar.gz
```

After the tarballs have been downloaded and extracted into the directory you passed in during `configure` (denoted below by the variable `$YOUR_DATA_DIR`), create the following files so libpostal's ```make``` doesn't attempt to download the data again:

```
echo $(date -u) > $YOUR_DATA_DIR/libpostal/last_updated
echo $(date -u) > $YOUR_DATA_DIR/libpostal/last_updated_parser
echo $(date -u) > $YOUR_DATA_DIR/libpostal/last_updated_language_classifier
echo "v1" > $YOUR_DATA_DIR/data_version
```

Or if you can whitelist those 5 URLs (including https://libpostal.s3.amazonaws.com/models/address_parser/latest and https://libpostal.s3.amazonaws.com/models/language_classifier/latest), then `make` should run normally.

**Comment by gabrielahrlr** [comment]
No luck! After several attempts, first downloading the data from those URLs didn't work. Then  we downloaded the data from a different computer with the libpostal_data script located in libpostal/src/ and copied it into $OUR_DATA_DIR/libpostal directory. We run make and it still attempts to download the data even though last_updated and everything else is already in the directory. Then a 56 error is thrown for unfinished jobs, and afterwards error 1 and 2.


mv -f .deps/near_dupe_test-near_dupe_test.Tpo .deps/near_dupe_test-near_dupe_test.Po
gcc -std=gnu99 -DHAVE_CONFIG_H -I.. -I/usr/local/include    -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR='"/geocoding_env/libpostal_data/libpostal"' -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O3  -MT utf8proc/near_dupe_test-utf8proc.o -MD -MP -MF utf8proc/.deps/near_dupe_test-utf8proc.Tpo -c -o utf8proc/near_dupe_test-utf8proc.o `test -f 'utf8proc/utf8proc.c' || echo './'`utf8proc/utf8proc.c
mv -f .deps/language_classifier_test-unicode_scripts.Tpo .deps/language_classifier_test-unicode_scripts.Po
./libpostal_data download all /geocoding_env/libpostal_data/libpostal
Checking for new libpostal data file...
libpostal data file up to date
make[2]: *** [all-local] Error 56
make[2]: *** Waiting for unfinished jobs....
mv -f utf8proc/.deps/near_dupe_test-utf8proc.Tpo utf8proc/.deps/near_dupe_test-utf8proc.Po
mv -f .deps/near_dupe_test-string_utils.Tpo .deps/near_dupe_test-string_utils.Po
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I.. -I/usr/local/include -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR=\"/geocoding_env/libpostal_data/libpostal\" -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O0 -D LIBPOSTAL_EXPORTS -MT libscanner_la-scanner.lo -MD -MP -MF .deps/libscanner_la-scanner.Tpo -c scanner.c -o libscanner_la-scanner.o >/dev/null 2>&1
mv -f .deps/libscanner_la-scanner.Tpo .deps/libscanner_la-scanner.Plo
make[2]: Leaving directory `/geocoding_env/libpostal/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/geocoding_env/libpostal'
make: *** [all] Error 2

**Comment by albarrentine** [comment]
Hm, so by default the `libpostal_data` script will still make at least 1 external request to check if there are new data files.

The good news is, if you already have the files extracted, you can run `./configure --datadir=/geocoding_env/libpostal_data --disable-data-download` and that will result in `libpostal_data` not being run at all.

**Comment by gabrielahrlr** [comment]
It worked!!! :) Many thanks!!

**Comment by vijayatgithub** [comment]
HI Team,

I was trying to download models manually .

Can someone help me to find the latest libpostal data file from S3.

The below links are not working.
https://libpostal.s3.amazonaws.com/models/address_parser/latest
https://d1p366rbd94x8u.cloudfront.net/libpostal/data/v1/libpostal_data.tar.gz


Below is the error message getting while accessing the link.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2KKXFQN877WN3HEY</RequestId>
<HostId>2Mp783YDTFDPNnQl3LEs6aQBiv0X/VNy1cfICelTIlijh0LHxJXfFrHI8tSSoJ6dYC4ezfklmYQ=</HostId>
</Error>

Please help me to get the LibPostalData.

thanks,
Vijay
