### ISSUE TITLE
JavaCPP integration

### ISSUE THREAD

**Issue by Maurice-Betzel** [openvenues/libpostal#290]
Dear community, i have initiated a libpostal [preset](https://github.com/Maurice-Betzel/javacpp-presets/tree/javacpp-presets-libpostal) on the JavaCPP project. Samuel Audet and myself succeded in getting the windows build up and running, but it was based on a prebuild dll. I wanted to integrate the build in JavaCPP preset as wel but got stuck on the following error:

`Detected platform "windows-x86_64"
Building for platform "windows-x86_64"
Installing "libpostal"
~/javacpp-presets/libpostal/cppbuild ~/javacpp-presets
downloading libpostal
unpacking libpostal
Starting windows-x86_64 build
/home/betzm/javacpp-presets/libpostal/cppbuild/windows-x86_64/libpostal-master
autoreconf: running: /usr/bin/autoconf --version | sed 1q >&2
autoconf (GNU Autoconf) 2.69

autoreconf: running: /usr/bin/autoheader --version | sed 1q >&2
autoheader (GNU Autoconf) 2.69

autoreconf: running: automake --version | sed 1q >&2
automake (GNU automake) 1.15.1

autoreconf: running: aclocal --version | sed 1q >&2
aclocal (GNU automake) 1.15.1

autoreconf: running: autopoint --version | sed 1q >&2
/usr/bin/autopoint (GNU gettext-tools) 0.19.8.1

autoreconf: running: libtoolize --version | sed 1q >&2
libtoolize (GNU libtool) 2.4.6

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force --verbose --warnings=no-portability
aclocal-1.15: found macro AM_PROG_VALAC in /usr/share/aclocal-1.15/vala.m4: 21
aclocal-1.15: found macro AM_PROG_UPC in /usr/share/aclocal-1.15/upc.m4: 9
aclocal-1.15: found macro _AM_PROG_TAR in /usr/share/aclocal-1.15/tar.m4: 23
aclocal-1.15: found macro _AM_SUBST_NOTMAKE in /usr/share/aclocal-1.15/substnot.m4: 12
aclocal-1.15: found macro AM_SUBST_NOTMAKE in /usr/share/aclocal-1.15/substnot.m4: 17
aclocal-1.15: found macro AM_PROG_INSTALL_STRIP in /usr/share/aclocal-1.15/strip.m4: 17
aclocal-1.15: found macro AM_SILENT_RULES in /usr/share/aclocal-1.15/silent.m4: 12
aclocal-1.15: found macro AM_SANITY_CHECK in /usr/share/aclocal-1.15/sanity.m4: 11
aclocal-1.15: found macro AM_RUN_LOG in /usr/share/aclocal-1.15/runlog.m4: 12
aclocal-1.15: found macro AM_PATH_PYTHON in /usr/share/aclocal-1.15/python.m4: 35
aclocal-1.15: found macro AM_PYTHON_CHECK_VERSION in /usr/share/aclocal-1.15/python.m4: 230
aclocal-1.15: found macro _AM_PROG_CC_C_O in /usr/share/aclocal-1.15/prog-cc-c-o.m4: 12
aclocal-1.15: found macro AM_PROG_CC_C_O in /usr/share/aclocal-1.15/prog-cc-c-o.m4: 47
aclocal-1.15: found macro _AM_MANGLE_OPTION in /usr/share/aclocal-1.15/options.m4: 11
aclocal-1.15: found macro _AM_SET_OPTION in /usr/share/aclocal-1.15/options.m4: 17
aclocal-1.15: found macro _AM_SET_OPTIONS in /usr/share/aclocal-1.15/options.m4: 23
aclocal-1.15: found macro _AM_IF_OPTION in /usr/share/aclocal-1.15/options.m4: 29
aclocal-1.15: found macro AM_CONFIG_HEADER in /usr/share/aclocal-1.15/obsolete.m4: 11
aclocal-1.15: found macro AM_PROG_CC_STDC in /usr/share/aclocal-1.15/obsolete.m4: 17
aclocal-1.15: found macro AM_C_PROTOTYPES in /usr/share/aclocal-1.15/obsolete.m4: 26
aclocal-1.15: found macro fp_C_PROTOTYPES in /usr/share/aclocal-1.15/obsolete.m4: 28
aclocal-1.15: found macro AM_PROG_MKDIR_P in /usr/share/aclocal-1.15/mkdirp.m4: 11
aclocal-1.15: found macro AM_MISSING_PROG in /usr/share/aclocal-1.15/missing.m4: 11
aclocal-1.15: found macro AM_MISSING_HAS_RUN in /usr/share/aclocal-1.15/missing.m4: 20
aclocal-1.15: found macro AM_MAKE_INCLUDE in /usr/share/aclocal-1.15/make.m4: 12
aclocal-1.15: found macro AM_MAINTAINER_MODE in /usr/share/aclocal-1.15/maintainer.m4: 16
aclocal-1.15: found macro AM_PATH_LISPDIR in /usr/share/aclocal-1.15/lispdir.m4: 14
aclocal-1.15: found macro AM_PROG_LEX in /usr/share/aclocal-1.15/lex.m4: 13
aclocal-1.15: found macro AM_SET_LEADING_DOT in /usr/share/aclocal-1.15/lead-dot.m4: 10
aclocal-1.15: found macro AM_PROG_INSTALL_SH in /usr/share/aclocal-1.15/install-sh.m4: 11
aclocal-1.15: found macro AM_INIT_AUTOMAKE in /usr/share/aclocal-1.15/init.m4: 29
aclocal-1.15: found macro _AC_AM_CONFIG_HEADER_HOOK in /usr/share/aclocal-1.15/init.m4: 186
aclocal-1.15: found macro AM_PROG_GCJ in /usr/share/aclocal-1.15/gcj.m4: 10
aclocal-1.15: found macro AM_EXTRA_RECURSIVE_TARGETS in /usr/share/aclocal-1.15/extra-recurs.m4: 16
aclocal-1.15: found macro AM_WITH_DMALLOC in /usr/share/aclocal-1.15/dmalloc.m4: 12
aclocal-1.15: found macro _AM_OUTPUT_DEPENDENCY_COMMANDS in /usr/share/aclocal-1.15/depout.m4: 12
aclocal-1.15: found macro AM_OUTPUT_DEPENDENCY_COMMANDS in /usr/share/aclocal-1.15/depout.m4: 71
aclocal-1.15: found macro _AM_DEPENDENCIES in /usr/share/aclocal-1.15/depend.m4: 26
aclocal-1.15: found macro AM_SET_DEPDIR in /usr/share/aclocal-1.15/depend.m4: 163
aclocal-1.15: found macro AM_DEP_TRACK in /usr/share/aclocal-1.15/depend.m4: 171
aclocal-1.15: found macro AM_CONDITIONAL in /usr/share/aclocal-1.15/cond.m4: 12
aclocal-1.15: found macro AM_COND_IF in /usr/share/aclocal-1.15/cond-if.m4: 23
aclocal-1.15: found macro AM_AUX_DIR_EXPAND in /usr/share/aclocal-1.15/auxdir.m4: 47
aclocal-1.15: found macro AM_PROG_AS in /usr/share/aclocal-1.15/as.m4: 11
aclocal-1.15: found macro AM_PROG_AR in /usr/share/aclocal-1.15/ar-lib.m4: 13
aclocal-1.15: found macro AM_AUTOMAKE_VERSION in /usr/share/aclocal-1.15/amversion.m4: 14
aclocal-1.15: found macro AM_SET_CURRENT_AUTOMAKE_VERSION in /usr/share/aclocal-1.15/amversion.m4: 33

aclocal-1.15: error: aclocal: file '/msys64/usr/share/aclocal/xsize.m4' does not exist
autoreconf: aclocal failed with exit status: 1
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)`

This happens within the preset Maven build, if i build the lib from the mingw64 console everything runs fine.
More [context](https://groups.google.com/forum/#!topic/javacpp-project/8MXEYVq4XF8)

**Comment by AeroXuk** [comment]
Not being familiar with how JavaCPP works, assuming you also use MSys2/MingW64, I would recommend you look at the [AppVeyor config file](https://github.com/openvenues/libpostal/blob/master/.appveyor.yml).

You'll see within the build script, the environment path is modified to ensure the prefered versions of the build tools are picked up for a 64 bit build it get set to something like `C:\msys64\mingw64\bin;C:\msys64\usr\bin;$PATH`. 

Not sure if that's the issue but because you have a `does not exists` error with m4 it might be related.

**Comment by Maurice-Betzel** [comment]
That pointed me to the right direction, the following addition made the build work:

`cwd=$(pwd)
    bash -lc "cd $cwd && autoreconf -fi --warning=no-portability"`
