### ISSUE TITLE
building for win32?

### ISSUE THREAD

**Issue by jepp** [openvenues/libpostal#306]
The windows instructions given are great for building the 64bit version, but I'm having problems figuring out how I could build a 32bit one. Unfortunately, that's what we're stuck with right now. I know I can download it from AppVeyor but I'm trying to broaden my horizons.

**Comment by albarrentine** [comment]
So, I did not work on the Windows build, but check the steps in the [Appveyor config](https://github.com/openvenues/libpostal/blob/master/.appveyor.yml). Seem to recall there being a flag called `/LARGEADDRESSAWARE` that needs to be set for everything to work on 32-bit. Also need to download the 32-bit version of msys2, etc. Feel free to add instructions to the README if you get it working.

**Comment by jepp** [comment]
Thanks. Unfortunately, this isn't really my typical toolchain so I'm out of my element. I'm actually trying the LocalAppveyor projects right now to see if I can cheat a little bit that way.

The reason I'm investigating is that I got the 32bit dll from AppVeyor wrapped in Delphi 2007 (big legacy  project that I want to integrate this into) and libpostal_parse_address works correctly but libpostal_expand_address always returns 1 result that's not actually expanded. Doesn't happen in the .net console tester, even using the same datadir.

So I'm trying to 100% make sure everything is set up right with the 32bit dll. I found it a bit odd that the 32bit one depended on libgcc_s_dw2-1.dll but the 64bit one seemed only use standard system dlls.

**Comment by albarrentine** [comment]
I don't have any Windows machines, so this is very far removed from my element.

What's the input to expand_address and what is it returning? Does the `libpostal` client program return > 1 expansion? Does the `language_classifier` program return anything for the same input?

**Comment by jepp** [comment]
32bit windows program with default options:
781 Franklin Ave Crown Heights Brooklyn NYC NY 11216 USA
returns
781 franklin ave crown heights brooklyn nyc ny 11216 usa

> $ ./libpostal.exe "Franklin Ave Crown Heights Brooklyn NYC NY 11216 USA"
> franklin avenue crown heights brooklyn nyc new york 11216 usa
> franklin avenue crown heights brooklyn nyc ny 11216 usa

> $ ./language_classifier.exe "Franklin Ave Crown Heights Brooklyn NYC NY 11216 USA"
> Languages:
> 
> en (1.000000)
>

**Comment by albarrentine** [comment]
Ok, so that looks like the C build worked fine.

What is "32bit windows program with default options"? Is that .net, a C program, something else?

**Comment by jepp** [comment]
Sorry, by that I'm referring to the 32bit Delphi program I built with the DLL headers I translated. As far as I can tell, I got the headers right. I'm getting address parsing to work perfectly. By "default options", I mean I'm calling libpostal_get_default_options (which gives me results that match what I get when I do this in the successfully working 64bit LibPostalNet project I built) and just passing those back in to the libpostal_expand_address call.

**Comment by jepp** [comment]
Okay, now I just feel dumb. See if you can spot the obvious mistake:
>  if not libpostal_setup_datadir(dataDir)
>      or not libpostal_setup_parser_datadir(dataDir)
>      or not libpostal_setup_language_classifier then

X)

Yes, I should have called
>      or not libpostal_setup_language_classifier_datadir(dataDir) then

Now it works just fine. Thanks for the attempt to help me.

**Comment by albarrentine** [comment]
Ah no worries. It seemed like something to do with the language classifier. Glad it worked out! Never imagined libpostal would be usable from Delphi, that's a blast from the past! (1998 in my case).

**Comment by philhutch50** [comment]
@jepp Hi, I am trying to set this library up for Delphi as well, do you code you would be willing to share please?
Thanks
Phil
