### ISSUE TITLE
Issue with directory names with spaces.

### ISSUE THREAD

**Issue by kjanjua26** [openvenues/libpostal#316]
I am currently running MACOS v10.13.1 and trying to compile libpostal.

I did the following so far:
`git clone https://github.com/openvenues/libpostal`
`cd libpostal`
`./bootstrap.sh`

These steps work fine. However, when `make` is run, there is issue with directory not found and it gets stuck there. I solved the permission errors, however still there are issues with this. However, I know that directory exists and when I cd into the directory, it executes without any problem.
I figured the solution i.e. my directories were named as: example 1/example 2/libpostal etc.
When I cd into the directory, I use `cd "example 1/example 2/libpostal"` which works fine. However, the `make` doesn't consider this and thus the error.

Please push a new update to handle such cases or add a disclaimer regarding this.

**Comment by albarrentine** [comment]
Hm, that's an issue with autotools rather than libpostal, so not much we can do unfortunately. In general when working with Unix-y tools, it's always a safer bet to use underscores instead of spaces.
