### ISSUE TITLE
Unable to locate package libsnappy-dev

### ISSUE THREAD

**Issue by pasupulaphani** [openvenues/libpostal#32]
May I know the repo for libsnappy-dev to pull the package from. (is it 32 bit lib)

```
root@550fc05b4ed1:/app/user# apt-get install libsnappy-dev autoconf automake libtool pkg-config
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libsnappy-dev

root@550fc05b4ed1:/app/user# cat /etc/issue
Ubuntu 14.04.2 LTS \n \l
```

**Comment by thatdatabaseguy** [comment]
It should definitely be in 14.04: http://packages.ubuntu.com/trusty/libsnappy-dev.

Try running ```apt-get update``` first and then installing?

**Comment by pasupulaphani** [comment]
Cheers @thatdatabaseguy 

I added 'deb http://cz.archive.ubuntu.com/ubuntu trusty main ' to sources.list as mentioned here 'http://packages.ubuntu.com/trusty/amd64/libsnappy-dev/download'.

followed by ```apt-get update``` solved the issue.
