### ISSUE TITLE
Extracting adresses from free text ?

### ISSUE THREAD

**Issue by parisni** [openvenues/libpostal#322]
Hi!

---
#### Here's how I'm using libpostal

I am wondering if  libpostal can be used in some way to extract adresses from free text. My goal is to make name entity recognition:

---

    parse_address('I am going to the Book Club 100-106 Leonard\
    St Shoreditch London EC2A 4RH, United Kingdom to have a dring')
     {"the Book Club 100-106 Leonard St Shoreditch London EC2A 4RH, United Kingdom"}

Thanks a lot

**Comment by albarrentine** [comment]
Hey @parisni, I've written about this a few times before, but no, it's not a goal of libpostal to extract addresses. The parser is designed for strings that are already known to be addresses/geographic text (geocoder input, free-text address fields in a database, etc.) and will label every token as an address component. I know a lot of users who are writing scrapers, bots, etc. want this feature, but it's a very different machine learning problem and it would be more difficult to obtain a large, suitable training set in multiple languages (or even in one language for that matter). Libpostal makes use of the fact that there are many high-quality sources of free, openly-licensed addresses with house number/street, etc. split out into components, as well as lat/lon so the other components like city/country, etc. can be inferred through reverse geocoding. We then take the component values (the desired output of our model) and reconstruct the input address, generating several variations, sometimes with random secondary units, different formats, etc.

The major difference in address extraction is the need to model the transition from non-address text to address text and back again (the "I am going to", etc.) As mentioned in #22, it might be possible to generate examples of this using Wikipedia links for formal third-person text, or possibly from something like Facebook posts that are tagged with places for informal text. However, I can easily see that being a 6 month project to get something as high-quality/robust as libpostal's parser, and I don't personally have a use case to justify that kind of time commitment.

**Comment by revolunet** [comment]
Hi @parisni , did ou find a solution to address extraction from raw text ?

**Comment by parisni** [comment]
@revolunet  yes. we annotated a corpus of 2k discharge summaries. And then trained a neural nerwork. https://github.com/strayMat/tag_serve
the f-mesure is .97 on adresses.

Then libpostal can be used to extract meaning-full information

**Comment by revolunet** [comment]
Thanks for sharing ;)
So you manually tagged addresses in 2k documents  ? Why not use openaddresses or similar ?
Is the result sharable ?

**Comment by revolunet** [comment]
As a noob in NER i'd love to understand how to achieve this starting with a manually crafted dataset. would you mind sharing the process ?
