### ISSUE TITLE
Issue with datadir - "expected absolute directory name for --datadir"

### ISSUE THREAD

**Issue by GiulioGiorcelli** [openvenues/libpostal#323]
Hi there,

I'm trying to build the library on a Linux VM with Ubuntu but when I get to the part where I should run: 

./configure --datadir[mypath]

I get this error:
configure: error: expected an absolute directory name for --datadir: "mypath"

The path that I am using is the following: /home/username/Desktop/postal. I checked running cd <path> and the path is visible and it does exist. I tried with and without quotation marks but I keep getting the same error message.

Any help would be greatly appreciated.

Giulio

**Comment by albarrentine** [comment]
`./configure --datadir=/home/username/Desktop/postal` should work. Note: the square brackets are just used to illustrate options on the command line and should not be used literally.

The path does have to be absolute, which is an autotools thing rather than specific to libpostal.

**Comment by GiulioGiorcelli** [comment]
It worked, thank you. Stupid mistake on my end.

I have tested libpostal and it works great, great work. One quick question - is there away to limit the results of the parser and the expander to only US addresses?

**Comment by albarrentine** [comment]
No problem!

The expansion and deduping APIs have an option for languages, but not countries. The parser is a global model, but empirically it works well for single-country data sets too (including in the US - I personally use it for parsing statewide voter file addresses and it's been great).

One user has trained smaller per-country models for use on embedded devices. The training data for libpostal is publicly available, and each example includes country and language, so what they did in that case was `grep` for the country of interest in the various files and create a smaller training set. See https://github.com/rinigus/geocoder-nlp (it uses the previous version of libpostal still but I think the only major difference is that `build_geodb` is no longer used) and #132 for details.

**Comment by GiulioGiorcelli** [comment]
Got it, thank you!
