### ISSUE TITLE
libpostal installation failed

### ISSUE THREAD

**Issue by liufang94** [openvenues/libpostal#327]
Hi AI, 

I just tried to install latest libpostal and run address_parser, the installation went through but address_parser failed to start. Here are the details:

Install libpostal on my Mac OS. 
I tried two Mac OS and both have same problem.

git clone https://github.com/openvenues/libpostal
cd libpostal
./bootstrap.sh
./configure --datadir=$PWD
make (tried make -j4 on another Mac, same problem, guess -j4 doesn't matter much)
sudo make install

cd libpostal/src
./address_parser
Loading models...
ERR   Error loading transliteration module, dir=(null)
   at libpostal_setup_datadir (libpostal.c:266) errno: No such file or directory

I also tried one linux env and not able to start jpostal's address parser.  I didn't try libpostal/src/address_parser on that linux machine because my account doesn't have necessary privilege, but I guess the root cause is same.
sudo ldconfig

Could you help take a look?

Thanks a lot!

Tracy

**Comment by jeremy-im** [comment]
I am seeing permission problems on the S3 bucket from which the data is downloaded. Every request made by `libpostal_data` gets `<Error><Code>AllAccessDisabled</Code>` but that error does not cause the script to fail and so `make` incorrectly believes the data was successfully downloaded. Here is the script output:

    Checking for new libpostal data file...
    libpostal data file up to date
    Checking for new libpostal encoding="UTF-8"?>...
    libpostal encoding="UTF-8"?> up to date
    Checking for new libpostal encoding="UTF-8"?>...
    libpostal encoding="UTF-8"?> up to date

**Comment by liufang94** [comment]
@jeremy-im do you know who can help on the s3 permission issue?

**Comment by albarrentine** [comment]
@liufang94 @jeremy-im the Mapzen servers were finally shut down recently, and that included the AWS account that libpostal was using. The releases have been moved to Github now, and there's a pull request that I'm building now in #328 which fixes this issue.

**Comment by albarrentine** [comment]
The models have now been moved to Github on the download side. Still need to convert the upload side of the script to Github releases for pull requests and the next iteration of the training data.

The 2017 training data has been moved to the Internet Archive, and that will be the home of future data sets.

**Comment by liufang94** [comment]
Thanks very much for the quick fix, AI.
Just want to confirm, does this mean we can install libpostal without
problem now?

**Comment by albarrentine** [comment]
Yes. Not all operating systems have been tested, but it at least works for Mac, Ubuntu, and Windows.

**Comment by liufang94** [comment]
That’s great, thanks!

**Comment by liufang94** [comment]
Hi AI,

Currently we always download the latest libpostal and make / install
locally. When this issue happened, we were not able to install it.

I am thinking, can I clone /make libpostal on another machine, and when I
need it, I can just copy files (both source files and data files) from that
machine to my machine, run some install commands if necessary, and my
colleague can get the same version too. In this way, even data location has
problem, we can still use libpostal.
We can periodically update libpostal on that dedicate machine.

Is it possible to do that?

Thanks!

**Comment by albarrentine** [comment]
Hi Tracy, yes, that's a good idea. It's possible to build the library without the data/models using `./configure --disable-data-download` (people often use this approach with e.g. Docker setups), then can keep a shared copy of the files either in some known location on the network or on a shared filesystem like S3 or HDFS, and update them periodically.

**Comment by liufang94** [comment]
Thanks AI. With "./configure --disable-data-download", will we be able to
actually use it or not?
If we will still need to download data/models when using it, can we
download the data/models to somewhere too? We can regularly update it.
Then we can download the shared copy of code and shared copy of data/models
separately.

**Comment by albarrentine** [comment]
The model files are required to use libpostal, so `--disable-data-download` will just allow building a package and configuring a datadir separately from downloading the models. The models themselves can be downloaded with the script `libpostal_data download all $DATA_DIR/libpostal`. That script can either be found in `src` or in the bin directory (usually `/usr/local/bin` on *nix) after install.

**Comment by liufang94** [comment]
Got it, thanks a lot AI!

**Comment by pkennel** [comment]
Hi there @albarrentine .  Just checking in here, we'd love to build libpostal over here from your releases but see that this commit only made it to master.  Just checking, are you planning a release any time soon?  Thanks!

**Comment by albarrentine** [comment]
@pkennel added the Github release commit to v1.1-alpha, feel free to build from that tag.
