### ISSUE TITLE
Could Not Find Snappy

### ISSUE THREAD

**Issue by maxhawkins** [openvenues/libpostal#33]
When I run ./configure it fails with

    configure: error: Could not find snappy

I have Snappy installed using homebrew. However, my homebrew is in a non-standard location (~/.homebrew). I believe this is causing the issue.

I'm not familiar enough with Autoconf to fix it myself. Is there a way to fix in the Makefile or will I have to change my environment?

**Comment by thatdatabaseguy** [comment]
Hey Max - for a non-standard location, you'll just want to set CFLAGS and LDFLAGS, like this (I'm making up directories and snappy version but you get the idea):

```
./configure CFLAGS=-I/your/home/.homebrew/snappy/1.1.3/include LDFLAGS=-L/your/home/.homebrew/snappy/1.1.3/lib --datadir=/your/data/dir
```

**Comment by maxhawkins** [comment]
Thank you. That worked great for me.

It's too bad snappy doesn't ship with a pkg-config!

**Comment by 13k** [comment]
This isn't true anymore (at bcf6b3cc683d58d22e73adee00256bbf8c7641d1). Top-level Makefile is fine, but subdirs Makefiles ([1], [2]) override `CFLAGS` and the environment info is lost to them.

[1]: https://github.com/openvenues/libpostal/blob/bcf6b3cc683d58d22e73adee00256bbf8c7641d1/src/Makefile.am#L3-L10
[2]: https://github.com/openvenues/libpostal/blob/bcf6b3cc683d58d22e73adee00256bbf8c7641d1/src/sparkey/Makefile.am#L1

**Comment by thatdatabaseguy** [comment]
There's a change in parser-data that allows CFLAGS to be passed in. Merged it into master in https://github.com/openvenues/libpostal/pull/142.

The CFLAGS override is deliberate, as scanner.c won't compile in a reasonable amount of time with higher optimization levels. So have to force ```-O0``` no matter what the user specified. Other things like include dirs should be fair game.

**Comment by 13k** [comment]
thanks @thatdatabaseguy
