### ISSUE TITLE
How to train the model with private data?

### ISSUE THREAD

**Issue by dcai5000** [openvenues/libpostal#346]
Hi,

I have a collection of data for India and I would like to obtain a proprietary model with this data collection.

I looked around the available documentation but I was unable to find the process to do that myself..

Question:

Do we have a full documentation on how to prepare our own data and run individual pipeline to create a proprietary model by myself?

---
#### My country is
USA

**Comment by albarrentine** [comment]
This has been discussed in a few other issues, but we don't encourage training custom models (and cannot provide support for models trained on proprietary data sets as it's difficult-to-impossible to debug a parser that's not performing as well as expected without knowing how the training data was constructed).

In general we'd like to get more addresses for India out in the open. What we have is several orders of magnitude less than the population, and does not cover all regions of the country proportionally, so it would be great if there are sources, especially with landmarks, etc. that can be opened up and used in this project.

**Comment by dcai5000** [comment]
Thanks a lot for the answer and the patience.

**Comment by avimar** [comment]
@albarrentine I couldn't find an email address for you.

Are you available for consulting? i.e. to train libpostal on a specific area and specific (messy) addresses?
