### ISSUE TITLE
403 error on S3 bucket for libpostal_data.tar.gz

### ISSUE THREAD

**Issue by threatstop** [openvenues/libpostal#366]
Hi!

I am seeing a 403 error when the build is attempted to download the libpostal_data file from S3.

---
#### My country is
USA/California

---
#### Here's how I'm using libpostal
Address validation for web app

---
#### Here's what I did
* Ubuntu 14.04
* libpostal.1.0.0.tar.gz
* Ran ./configure --datadir=/srv/postal
* Build completes but using the library fails

---
#### Here's what I got
ERR   Error loading transliteration module, dir=(null)
   at libpostal_setup_datadir (libpostal.c:1047) errno: No such file or directory

./src/libpostal_data download all /srv/postal/
is silently failing because it's getting a 403 

```
++ curl -sI http://libpostal.s3.amazonaws.com/data/v1/libpostal_data.tar.gz -z 'Jan  1 00:00:00 1970' --remote-time -w '%{http_code}' -o /dev/null
+ '[' ']'
**+ echo 'libpostal data file up to date'**
libpostal data file up to date
++ curl --silent http://libpostal.s3.amazonaws.com/models/address_parser/latest
+ latest_parser='<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AllAccessDisabled</Code><Message>All access to this object has been disabled</Message><RequestId>4CEA5C92C38C872F</RequestId><HostId>DeNoClUeiQYbaanv2dswWtpswPh/O3Mee8m7CE/3toBKe4esCn+Ny8n8o0Pf44NlZXtOdDn0pFI=</HostId></Error>'
+ parser_s3_prefix='models/address_parser/<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AllAccessDisabled</Code><Message>All access to this object has been disabled</Message><RequestId>4CEA5C92C38C872F</RequestId><HostId>DeNoClUeiQYbaanv2dswWtpswPh/O3Mee8m7CE/3toBKe4esCn+Ny8n8o0Pf44NlZXtOdDn0pFI=</HostId></Error>'
```

There seems to be two issues:
* Issue #1: permission error

```
# curl -vI http://libpostal.s3.amazonaws.com/data/v1/libpostal_data.tar.gz
< HTTP/1.1 403 Forbidden
< x-amz-request-id: 0CD32EFB2312E306
< x-amz-id-2: qWFmjRTCNVj35RT8vczGRQHNPs+KAYsuOqlFr78rFO6IUUPqtpchg0oH6NjYgJfvt2IKu9sMH44=
```

* Issue #2: the curl error gets interpreted as the presence of an up-to-date data file.

**Comment by AeroXuk** [comment]
The version of the build script that was in v1.0.0 has been replaced as the models are no longer hosted on Amazon s3.
If you wish to manually download them they can be found on the release tab:
https://github.com/openvenues/libpostal/releases/tag/v1.0.0

The latest copy of the download script (below), has been updated to work with the new GitHub hosted models:
https://github.com/openvenues/libpostal/blob/master/src/libpostal_data

The issues around `403 Forbidden` being interpreted as success will possibly need a patch making for it incase the models are migrated again in future.

**Comment by threatstop** [comment]
Thanks. I will wait for the next production release to upgrade, and will download the file manually in the meantime,
