### ISSUE TITLE
Data files is loaded twice

### ISSUE THREAD

**Issue by drnextgis** [openvenues/libpostal#38]
`make` downloads data files from S3 - ok, but when I type `sudo make install` - it downloads them again.

```
========================= Installation results ===========================
Making install in src
make[1]: Entering directory `/home/rykov/git/libpostal/src'
Making install in sparkey
make[2]: Entering directory `/home/rykov/git/libpostal/src/sparkey'
make[3]: Entering directory `/home/rykov/git/libpostal/src/sparkey'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/home/rykov/git/libpostal/src/sparkey'
make[2]: Leaving directory `/home/rykov/git/libpostal/src/sparkey'
make[2]: Entering directory `/home/rykov/git/libpostal/src'
./libpostal_data download all /home/rykov/tmp/libpostal
Checking for new libpostal data file...
Warning: Illegal date format for -z, --timecond (and not a file name). 
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
```

Ubuntu 14.04

**Comment by thatdatabaseguy** [comment]
```libpostal_data``` should run on ```make install``` but it saves the revision date for each file it downloads and checks with the server when it's run to see if there's a newer version of the files available.

Looking at the warnings, this may be an issue: ```Warning: Illegal date format for -z, --timecond (and not a file name). ``` One of the boxes we use regularly is Ubuntu 14.04 (the Travis CI build also uses Ubuntu, version 12.04). Haven't encountered that issue yet, so we should check for differences in environments.

Two questions:

1. Did the first download succeed? It's possible that it may have run out of disk space (if you run ```du -h``` on the libpostal data directory if should show something like 2.2G)
2. Can you check ```curl --version```?

**Comment by drnextgis** [comment]
1. Yes, the first download is ok. I have a lot of free disk space:

    ```
    $ du -h ~/tmp | grep libpostal
    8.8M	/home/rykov/tmp/libpostal/address_expansions
    19M	    /home/rykov/tmp/libpostal/transliteration
    406M	/home/rykov/tmp/libpostal/address_parser
    348K	/home/rykov/tmp/libpostal/numex
    1.1G	/home/rykov/tmp/libpostal/geodb
    678M	/home/rykov/tmp/libpostal/language_classifier
    2.2G	/home/rykov/tmp/libpostal
    ```

2. curl version:

    ```
    $ curl --version
    curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
   Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
    Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
````

**Comment by thatdatabaseguy** [comment]
Ok, that all looks fine. Does this command return anything? ```date -r /home/rykov/tmp/libpostal```

Also, can you post the output of ```cat /home/rykov/tmp/libpostal/last_updated``` so I can see which date format is being used?

**Comment by drnextgis** [comment]
```
$ date -r /home/rykov/tmp/libpostal
Thu Mar 10 21:56:43 OMST 2016
rykov@work:~$ cat /home/rykov/tmp/libpostal/last_updated
Thu Mar 10 21:40:29 OMST 2016
```

**Comment by thatdatabaseguy** [comment]
curl seems to have a problem parsing that timezone, but we should be using UTC dates in any case, so I've fixed that with https://github.com/openvenues/libpostal/commit/0d7f9f2032c825d4a809072a7f53761c495a6a26.

First, let's fix your existing dates so you don't have to download the files yet again.

```
for filename in /home/rykov/tmp/libpostal/last_updated*;
do
    cat "$(date -u)" > $filename
done;
```

Then you can pull the latest changes from the repo, run ```make``` or ```sudo make install``` and the data files won't be downloaded again.

**Comment by drnextgis** [comment]
Thanks for quick response. Now it works as expected.
