### ISSUE TITLE
problems detecting UK postcodes

### ISSUE THREAD

**Issue by fabriziomoscon** [openvenues/libpostal#39]
Great library!

I found some problem parsing UK postcodes. I will post just a couple of example but I got more if necessary

```
{ input: '318 Upper Street, N1 2XQ London',
  expanded: 
   [ '318 upper street n1 2xq london',
     '318 upper street n 1 2xq london',
     '318 upper street north 1 2xq london' ],
  parsed: 
   [ { value: '318', component: 'house_number' },
     { value: 'upper street', component: 'road' },
     { value: 'n1', component: 'postcode' },
     { value: '2xq', component: 'suburb' },
     { value: 'london', component: 'city' } ] }

{ input: '21, Kingswood Road SW2 4JE, London',
  expanded: 
   [ '21 kingswood road sw2 4je london',
     '21 kingswood road sw 2 4je london',
     '21 kingswood road southwest 2 4je london' ],
  parsed: 
   [ { value: '21', component: 'house_number' },
     { value: 'kingswood road', component: 'road' },
     { value: 'sw2', component: 'postcode' },
     { value: '4je', component: 'suburb' },
     { value: 'london', component: 'city' } ] }

```

**Comment by thatdatabaseguy** [comment]
Thanks!

I think it might have to do with the ordering. The UK addresses the model is trained on are mostly formatted like this:

21, Kingswood Road London SW2 4JE

Which will be parsed correctly:
```
{
  "house_number": "21",
  "road": "kingswood road",
  "city": "london",
  "postcode": "sw2 4je"
}
```

Is the format you posted common? I'll be retraining the model soon and can add several formats and/or mix up the admin components so the model relies less on structural features and sees many different variations.

For the expansions, one of the options is split_alpha_from_numeric, which separates tokens like "RN7" into two tokens so it expands correctly to "route nationale 7" in French. An English example would be "CR21" expanding to "county road 21". One way to avoid applying those kinds of expansions in UK postal codes which need to be single tokens (like SW2) is to first parse the address, then expand with the appropriate options for each component (split_alpha_from_numeric is only necessary for street names, not for postal codes). In the next release I may add a combined method which does both parsing and limited expansions per component.

**Comment by fabriziomoscon** [comment]
Hi,
Yes those are pretty common format. I tested the library over ~200 addresses coming from Google places API. I have a full database with those.
I think many apps like ours are using Google maps for geocoding.

Also I read your blog post and understood this library would be particular useful for apps and delivery services. So you might want to expose a function that parse the address according to a specific county since in some cases the user/developer knows exactly which county corresponds to the input address. Also considering the long tail off apps in the "on-demand" economy are single country based.

I hope this would help. If necessary I can share our addressed in anonymous manner so you can have a look for yourself.

**Comment by dianashk** [comment]
Similar issue in Norway.

`Sars` gate 2 A, 562 OSLO`

results in 

```
{
  "road": "sars` gate",
  "house_number": "2 a 562",
  "city": "oslo"
}
```

**Comment by thatdatabaseguy** [comment]
@dianashk Norway appears to be a separate issue. Libpostal has two modes for handling numeric tokens. If a number is part of a known postcode (from GeoNames), an input feature is added to denote a postcode match, otherwise each digit in the number is converted to an uppercased "D" (all other text is lowercased so the uppercased D doesn't conflict with natural occurrences of the letter "D") so the parser doesn't need to see every potential 3-digit number in every context, it just sees "DDD oslo".

In this case it looks like GeoNames lists 4-digit postcodes for Norway, so 562 isn't matching the gazetteer and thus is getting treated as a simple 3-digit number (which will be more difficult to distinguish from a house number since that's almost always what a 3-digit number is, in any context).

This can be fixed relatively simply during preprocessing by deriving an additional postal code data set from the training data (OSM) to supplement the GeoNames postcodes.

**Comment by thatdatabaseguy** [comment]
@fabriziomoscon  libpostal 1.0 can handle this type of address if you download latest. We have [a formatting config](https://github.com/openvenues/libpostal/blob/master/resources/formatting/global.yaml) now which allows us to train on different formats than the standard ones in [address-formatting](https://github.com/OpenCageData/address-formatting) by switching components around with random probabilities. 10% of the time, for addresses in the UK, we move the postcode before the city. If there are other formatting discrepancies between your addresses and the standard, feel free to add them to the config and those types of training examples will be generated on the next build.

Also, the training data now includes examples of virtually every single postcode in the UK from GeoPlanet, which contained over 1 million UK postcodes

**Comment by thatdatabaseguy** [comment]
@dianashk going to close the UK issue. For Oslo, 1.0 identifies the 3-digit postcodes correctly. It has one problem with "Sars gate 2 A" in that it classifies the "2 A" as part of the road when it's written with a space. In Norway I believe the usual way to write it is "2A" and that's what [OSM](https://www.openstreetmap.org/node/3138854508#map=19/59.91881/10.76714) says also, so guessing most of its examples are without spaces (when a space is added, it's a different tokenization in libpostal). I can fix for next build by just separating numeric + alpha or alpha + numeric house numbers into two tokens some random percentage of the time (which is probably valid everywhere in the world, not just Norway).
