### ISSUE TITLE
example code?

### ISSUE THREAD

**Issue by boshkins** [openvenues/libpostal#4]
Hello,
Would you kindly provide some code examples? 
Thank you! 
Anatoly

**Comment by thatdatabaseguy** [comment]
Hey Anatoly,

I see you're building an offline geocoder - libpostal should be quite helpful. Its goal is to serve as a preprocessing step for geocoders at index/query time before text hits the search engine, transforming geographic strings into the sorts of strings full-text search engines are designed to process.

While libpostal has not technically been released yet, it should be relatively painless to prototype something in C/C++ at this point. Just know that the API may change. The project builds with a command-line interface for testing general address expansion, which also serves as a code example:

- https://github.com/openvenues/libpostal/blob/master/src/main.c

The following gist has a few contrived examples of how to use the command-line tool and showcase the range of what libpostal can currently do with different types of input:

- https://gist.github.com/thatdatabaseguy/f3ca09b1af6946bbb953

At this point the API requires a language code (not a country code) for the input query, which in the geocoder setting ought to be guessable from locale settings. 

If you need something more robust in the immediate term, you can try something like Google's compact language detector: https://github.com/CLD2Owners/cld2. This is designed for web documents and doesn't always return for short geo queries. libpostal has its own language classifier in the works which is specifically tailored to geographic strings, learned from all of OSM, and very accurate, even more so if the country is known.

The other major feature you may be interested in is the international address parser. That's partially pushed to Github, but is code-complete and is currently being tested.

Hope that's helpful.

**Comment by boshkins** [comment]
Hi Al,
Just what I was looking for, thank you!
Anatoly
