### ISSUE TITLE
Postal address classification.

### ISSUE THREAD

**Issue by hifall** [openvenues/libpostal#417]
Hi!

I've checked out the documentation, but I can't find if libpostal has an interface to take a piece of text as input, and return if the text is actually postal address.

For example, isAddress("This is not an address.") returns false.

Thanks!

**Comment by antimirov** [comment]
There is no such interface, it's not in the project's scope:

> Non-goals
> * **Verifying that a location is a valid address**
> * Actually geocoding addresses to a lat/lon (that requires a database/search index)

**Comment by hifall** [comment]
I was aware of that "Verifying that a location is a valid address" line, though I thought it referred to mapping a textual address string to one in the physical world, which is different than what I asked about.

Thanks for your reply.

**Comment by hifall** [comment]
If that's the case, should I just call libpostal_parse_address and check if it returns NULL. If so, the passed in string is not an address?

My situation is like this: I have a large body of text, where only some lines of it are addresses, while others are not. Therefore, for each line, I need to check if it's an address before moving on to parse it.

**Comment by antimirov** [comment]
I would say you can do something like that. You can require an address to always contain a street and that could be a start. Or combinations of street+house number, city+street, etc.

**Comment by hifall** [comment]
Good to know. Thanks for the suggestion!
