### ISSUE TITLE
By default SSE2 flags wrongly set on ARM CPU

### ISSUE THREAD

**Issue by AeroXuk** [openvenues/libpostal#433]
When following the compile instructions within the README.md of this repo on an ARM cpu (Raspberry Pi 4). SSE2 compile flags get set by default, even though the processor doesn't support them.

Rerunning configure with the `--disable-sse2` flag or removing the lines below allows a successful build.

https://github.com/openvenues/libpostal/blob/21601eb4b8941b8d6d9b795b1d6db4bd376f5b28/configure.ac#L75-L87

The `--disable-sse2` configure flag is not mentioned within the README.md compile instructions (allowing it to be missed).

Alternatively, it might also be better to detect the supported cpu features using an m4 plugin (e.g. AX_EXT or similar)?

**Comment by AeroXuk** [comment]
Is it possible to automate the check for SSE2 support or put that the option `--disable-sse2` exists in the documentation on this repo.

**Comment by thehappycoder** [comment]
Same happens on Apple m1 and Graviton EC2 instances https://aws.amazon.com/ec2/instance-types/t4/

**Comment by missinglink** [comment]
Issues has duplicates https://github.com/openvenues/libpostal/search?q=disable-sse2&type=issues
