### ISSUE TITLE
contributing address test data

### ISSUE THREAD

**Issue by lushzero** [openvenues/libpostal#44]
I have about 100,000 US California commercial addresses as they were input by users and also a postal verified version of the same address. Is this useful to you folks and whats the best way to pass it along if it is (a big dump, excerpts, etc)? The data is public domain and unencumbered.

**Comment by thatdatabaseguy** [comment]
Sounds great! If the addresses are public domain and natural input, they should be useful for libpostal's parser and/or language training data. Our current commercial addresses mostly come from OSM, which is already split up into fields, so we have to synthesize the original input. US commercial addresses often have PO boxes, etc. that aren't as common in OSM, so it's almost certainly going to be useful to train on more hand-typed addresses.

My one question would be: is it kosher to publish post office verification data? Usually USPS charges for that service, but if the standardized forms are public domain as well, I'm happy to use them.

Re: passing along, if it's under 25MB, it's possible to attach a CSV directly to this Github issue (drag and drop into the text box) and I can pick it up from there.

**Comment by lushzero** [comment]
After some additional research I stumbled upon https://openaddresses.io/ . It has approximately 120 million of the 150 million valid US addresses. This is a deterministic problem in that addresses have to actually exist and if they exist they are in someone's database so that's probably the better resource.

Here are 67,000+ user input addresses with the exact postal deliverable forms, primarily businesses. Note there may be some erroneous quotes in user inputted data so some csv parsers may choke on those rows. It's a zipped .csv .

[exact4.csv.zip](https://github.com/openvenues/libpostal/files/185100/exact4.csv.zip)

**Comment by Rickasaurus** [comment]
The international list here might be a good target for foreign addresses in US script. https://www.irs.gov/Charities-&-Non-Profits/Exempt-Organizations-Business-Master-File-Extract-EO-BMF

**Comment by thatdatabaseguy** [comment]
@lushzero the libpostal 1.0 release is trained on over 1 billion addresses worldwide including most of the sources in OpenAddresses, and virtually every address in California (I think they're missing maybe 2 counties). Should encompass all of these. Closing unless there are any objections.
