### ISSUE TITLE
armv7 compile failure "conditional branch out of range"

### ISSUE THREAD

**Issue by PureTryOut** [openvenues/libpostal#443]
I'm trying to package `libpostal` on Alpine Linux. It compiled fine on all architectures (x86, x86_64, armhf, aarch64, ppc64le) _but_ armv7.

On armv7 it fails strangely:

```
/tmp/ccFggAdh.s:1377852: Error: conditional branch out of range
```

It prints this out _a lot_, just everytime with a different number after the "s".

**Comment by w0pr** [comment]
There seems to be a solution in issue  #349  given here: https://github.com/openvenues/libpostal/issues/349#issuecomment-394377793

**Comment by PureTryOut** [comment]
Well GCC doesn't know the `-mmarch64` flag. Besides, that would only apply for aarch64, not armv7 (which is 32-bit).

**Comment by w0pr** [comment]
> Well GCC doesn't know the `-mmarch64` flag. Besides, that would only apply for aarch64, not armv7 (which is 32-bit).

Ah, sorry; I missed the arch specific arch.

**Comment by PureTryOut** [comment]
I'm still experiencing this, is there a solution?

**Comment by PureTryOut** [comment]
Adding the flag `--with-cflags-scanner-extra=-marm` (taken from Ubuntu Touch and SailfishOS packaging) worked!

I'll close this issue but hopefully this helps out future packagers.
