### ISSUE TITLE
Wrong postcode picked up for Netherland Address

### ISSUE THREAD

**Issue by monika-1** [openvenues/libpostal#463]
Hi!

I was checking out libpostal, and saw something that could be improved.

---
#### My country is
I am testing a Netherland address.

---
#### Here's how I'm using libpostal
I have created a libpostal API which I am using in my java code.
API uses below maven dependency:

**org.bytedeco
libpostal-platform
1.1-alpha-1.5.1**

---
#### Here's what I did
Passed a Netherland Address: 
**Sixt B.V. Kruisweg 791, NL - 2132 NG Hoofddorp**

---
#### Here's what I got
{
  "house": "sixt b.v.",
  "road": "kruisweg",
  "postcode": "791",
  "country": "nl",
  "postcode": "2132",
  "road": "ng",
  "city": "hoofddorp"
}

---
#### Here's what I was expecting
I am expecting postcode: 2132 NG
 But I am getting two wrong postcodes: 2132 and 791

---
#### For parsing issues, please answer "yes" or "no" to all that apply.

- Does the input address exist in [OpenStreetMap](https://openstreetmap.org)?
  No
- Do all the toponyms exist in OSM (city, state, region names, etc.)?
Don't know
- If the address uses a rare/uncommon format, does changing the order of the fields yield the correct result?
  Not correct but if I am changing the order, the result will have only one poscode.
Example:
Address: Sixt B.V. Kruisweg 791, 2132 NG Hoofddorp NL
Result:
{
  "house": "sixt b.v.",
  "road": "kruisweg",
  "house_number": "791",
  "postcode": "2132",
  "road": "ng",
  "city": "hoofddorp",
  "country": "nl"
}

- If the address does not contain city, region, etc., does adding those fields to the input improve the result?
- If the address contains apartment/floor/sub-building information or uncommon formatting, does removing that help? Is there any minimum form of the address that gets the right parse?

---
#### Here's what I think could be improved
Netherland Address

**Comment by antimirov** [comment]
Hi Monika,

Your first address is in an unusual format:

> Sixt B.V. Kruisweg 791, NL - 2132 NG Hoofddorp

This is the actual address of that place, notice the proper lack of ', NL -' in the middle:

> Kruisweg 791, 2132 NG Hoofddorp

The postal code problem with the second example is well-known in libpostal the it has not been fixed yet, I think. My solution was to have a regexp to find 4 digits followed by 2 capital letters, so convert '2132 NG' into '2132NG'. This makes libpostal work properly.
