### ISSUE TITLE
Germany Address: wrong postcode picked up

### ISSUE THREAD

**Issue by monika-1** [openvenues/libpostal#464]
Hi!

I was checking out libpostal, and saw something that could be improved.

---
#### I am testing a **Germany** address.

---
#### Here's how I'm using libpostal
I have created a libpostal API which I am using in my java code.
API uses below maven dependency:
**<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>libpostal-platform</artifactId>
            <version>1.1-alpha-1.5.1</version>
 </dependency>**

---
#### Here's what I did
Address passed to libpostal:
**HILTON BONN BERLINER FREIHEIT 2 BONN53111 Germany**

---
#### Here's what I got
**{
  "house": "hilton bonn",
  "road": "berliner freiheit",
  "house_number": "2",
  "postcode": "bonn53111",
  "country": "germany"
}**

---
#### Here's what I was expecting
"city": "Bonn"
"postcode": "53111"

But I got postcode as Bonn53111

---
#### For parsing issues, please answer "yes" or "no" to all that apply.

- Does the input address exist in [OpenStreetMap](https://openstreetmap.org)?
  Don't know.
- Do all the toponyms exist in OSM (city, state, region names, etc.)?
  Don't know.
- If the address uses a rare/uncommon format, does changing the order of the fields yield the correct result?
  Yes
**Example** - 
Address: HILTON BONN BERLINER FREIHEIT 2 BONN 53111 Germany
Result:
{
  "house": "hilton bonn",
  "road": "berliner freiheit",
  "house_number": "2",
  "city": "bonn",
  "postcode": "53111",
  "country": "germany"
}

- If the address does not contain city, region, etc., does adding those fields to the input improve the result?
- If the address contains apartment/floor/sub-building information or uncommon formatting, does removing that help? Is there any minimum form of the address that gets the right parse?

---
#### Here's what I think could be improved
Germany addresses

**Comment by antimirov** [comment]
Hi Monika,

libpostal does not do spellchecking and string splitting, so it's up to you to fix the incorrect postcode 'Bonn53111'.
