### ISSUE TITLE
new stable tagged release

### ISSUE THREAD

**Issue by MichaelMarien** [openvenues/libpostal#477]
Hi!

would it be possible to make a new stable release and tag it? Currently there is just a 1.1alpha and before that a very old 1.0 version. We typically only use stable versions, unfortunately, in this case the 1.0 is broken (due to the data download not working, move from S3 to git I presume).

thanks a lot!

**Comment by MichaelMarien** [comment]
Any chance this could happen?

**Comment by brl0** [comment]
First of all, thanks for the great package.
Also thanks @MichaelMarien for the conda package.  It really simplifies the installation of libpostal.

A new tagged release really would be very helpful.

The upshot for the original package maintainers is that with a working conda package, most users on most platforms can simply be directed to do `conda install -c conda-forge libpostal` to get the package installed, which would hopefully significantly reduce the amount of support needed for users.

**Comment by albarrentine** [comment]
tag's changed to v1.1
