### ISSUE TITLE
Error running address_parser

### ISSUE THREAD

**Issue by SteveDevineSSalt** [openvenues/libpostal#478]
This is a after a fresh install on Windows 10 which appeared to not error

I get the following error.
$ ./address_parser "Longacre, Parbrook, Glastonbury, BA68PB"
Loading models...
ERR   Could not find parser model file of known type
 at address_parser_load (address_parser.c:215) errno:No such file or directory
ERR   Error loading address parser module, dir=Longacre, Parbrook, Glastonbury, BA68PB\address_parser
 at libpostal_setup_parser_datadir (libpostal.c:434) errno:No such file or directory

The Datafiles are present in the data directory I specified during configuration

**Comment by AeroXuk** [comment]
The first parameter of the address_parser is to override the libpostal data directory.
The address_parser app is an interactive one that will give you a prompt to enter the address once launched.

**Comment by SteveDevineSSalt** [comment]
Thanks. My problem is then that the app just hangs. I've left it for 20 minutes and do not get a prompt

**Comment by SteveDevineSSalt** [comment]
I reinstalled with the data directory under my MSYS folder structure and it now works fine e.g. libpostal is installed under /home/<User>/libpostal

and the datadir is installed under /home/<User>/libpostaldata
