### ISSUE TITLE
Dr-->doctor, St-->saint,  Rd S-->road san

### ISSUE THREAD

**Issue by reedzhao** [openvenues/libpostal#480]
Hi!  I am having strange output from expand() function.

---
#### My country is
Canada

---
#### Here's how I'm using libpostal
I am trying to de-duplicate real-estate listings by address.  Using php binding (https://github.com/openvenues/php-postal).

---
#### Here's what I did
For one listing, we often have multiple variants of street name:
```
232 James St S
232 James Street South
``` 

---
#### Here's what I got
```
\Postal\Expand::expand_address('232 James St S, Hamilton, ON');
// output
232 james saint san hamilton on

\Postal\Expand::expand_address('232 James Street South, Hamilton, ON');
// output
232 james street south hamilton on
```
As you can see, there `S-->san` breaks de-duping process.  Similar issue also happens to `dr->doctor`,`st-->saint`

---
#### Here's what I was expecting
These addresses should translate to the same thing:
`232 James St S.` & `232 James Street South`
 `2384 Rundle Rd S` & `2384 Rundle Road South`
`306 spring creek dr` & `306 spring creek drive`
``

---
#### For parsing issues, please answer "yes" or "no" to all that apply.

- Does the input address exist in [OpenStreetMap](https://openstreetmap.org)?
NO

- Do all the toponyms exist in OSM (city, state, region names, etc.)?
Yes

- If the address uses a rare/uncommon format, does changing the order of the fields yield the correct result?
No

- If the address does not contain city, region, etc., does adding those fields to the input improve the result?
No

- If the address contains apartment/floor/sub-building information or uncommon formatting, does removing that help? Is there any minimum form of the address that gets the right parse?
N/A

---

**Comment by nikmolnar** [comment]
@reedzhao I'm wondering why you closed this issue. Did you find a solution?

**Comment by reedzhao** [comment]
I came to the conclusion that it is impossible to get one correct expanded
address.

So we have to work with multiple possible expanded addresses.  The
dr--drive conversion accuracy does not affect the final outcome if we use
all expanded addresses.

**Comment by nikmolnar** [comment]
@reedzhao That makes sense, thanks!

**Comment by rabbiveesh** [comment]
I don't know if this is implemented in the bindings you're using, but
there's also an `expand_address_root` function which drops out common words
like that, making a considerably shorter list.

**Comment by nikmolnar** [comment]
@rabbiveesh Thanks for the tip, I will give that a try! I'm using the Python bindings.

**Comment by rabbiveesh** [comment]
There's also another interface available, the "near_dupes" family of
functions. The docs on them are limited though, so I'm still not sure how
to use them (and I wrote Perl bindings for them!)
