### ISSUE TITLE
Error loading address parser module errno:Not enough space windows

### ISSUE THREAD

**Issue by amrkamal2025** [openvenues/libpostal#486]
I compiled libpostal library and followed the instruction for windows and everything looks good and everything looks download correctly the data file that contains address_expansions, address_parser, ..etc is downloaded completely with size of 1.84 GB then i use the sample code for libpostal, after i link the library in QT IDE using

```
LIBS += D:\cook\libpostal\libpostal\src\.libs\libpostal.a
LIBS += D:\cook\libpostal\libpostal\src\.libs\libpostal.dll.a
LIBS += D:\cook\libpostal\libpostal\src\.libs\libscanner.a
INCLUDEPATH += D:\cook\libpostal\libpostal\src\
```

then I use this code to set the datadir and parser datadir then simple example of parse address

```
libpostal_setup_datadir("D:\\cook\\libpostal\\Data\\libpostal");
libpostal_setup_parser_datadir("D:\\cook\\libpostal\\Data\\libpostal");


// Setup (only called once at the beginning of your program)
if (!libpostal_setup() || !libpostal_setup_parser()) {
    exit(EXIT_FAILURE);
}

libpostal_address_parser_options_t options = libpostal_get_address_parser_default_options();
libpostal_address_parser_response_t *parsed = libpostal_parse_address("781 Franklin Ave Crown Heights Brooklyn NYC NY 11216 USA", options);

for (size_t i = 0; i < parsed->num_components; i++) {
    printf("%s: %s\n", parsed->labels[i], parsed->components[i]);
}

// Free parse result
libpostal_address_parser_response_destroy(parsed);

// Teardown (only called once at the end of your program)
libpostal_teardown();
libpostal_teardown_parser();

return 0;

```
but I got this error

```
ERR   Error loading address parser module, dir=D:\cook\libpostal\Data\libpostal\address_parser
 at libpostal_setup_parser_datadir (libpostal.c:434) errno:Not enough space
ERR   parser is not setup, call libpostal_setup_address_parser()
 at address_parser_parse (address_parser.c:1666) errno:Not enough space
ERR   Parser returned NULL
 at libpostal_parse_address (libpostal.c:267) errno:Not enough space

```
so what i did wrong, I have for sure space on my disk more than 100GB and i still got this error.

**Comment by w0pr** [comment]
>  errno:Not enough space

This is ENOMEM and refers to available RAM.

**Comment by amrkamal2025** [comment]
I'm using windows 10 and i compiled using msys32 and i test the msys64 now, is there any solution for this problem?

**Comment by w0pr** [comment]
> I'm using windows 10 and i compiled using msys32 and i test the msys64 now, is there any solution for this problem?

I used msys64, apart from that; having more memeory available?

**Comment by amrkamal2025** [comment]
how can I check, I have 16 GB ram iam using laptop lenovo Y5070 core I7 so i think for sure yes, i need more??

**Comment by AeroXuk** [comment]
If using 32bit you need to run this to make it large address space aware:
https://github.com/openvenues/libpostal/blob/790e24bc0a42801e43b1025a44d395686885f311/.appveyor.yml#L40-L45

If using 64bit make sure application and library are compiled as 64bit.

Also check that RAM usage isn’t at 100% in task manager while the app is running.

**Comment by amrkamal2025** [comment]
Thank you for the answer, but please can you tell me how to run it? using msys32? do i need to compile the library from begin or just run this will solve it?
if so please tell me the command to use to run it thank you.

**Comment by AeroXuk** [comment]
This is the powershell script that runs as part of the automated libpostal build.

The important bit is the call to the ‘edit in.exe’ passing the ‘/LARGEADDRESSAWARE’ parameter followed by the .exe file you compile. This was also run against the .dll files too.

This command run against the compiled .exe & .dlls allows windows programs to allocate over 2GB of memory in 32bit mode.

**Comment by AeroXuk** [comment]
I would recommend using msys64 launched from the msys64 start menu option to compile the library if your hardware supports 64bit

**Comment by amrkamal2025** [comment]
it worked Thank you very much I use this command 
editbin /LARGEADDRESSAWARE "D:\WorkPlace\CppProject\Systemview\build-libpostalTest-Desktop_Qt_5_13_2_MinGW_32_bit-Release\Final\libpostalTest.exe"

this editbin found in visual c++ 

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

it worked thank you very much, and sure I will make a 64 compile
