### ISSUE TITLE
Install libpostal in different location on disk to use in AWS EFS and Lambda

### ISSUE THREAD

**Issue by manycoding** [openvenues/libpostal#512]
I want to run a libpostal enabled code in Lambda. For that I could use EFS, the only thing which stops me is that I am not sure how to install libpostal bindings onto EFS and link them from Lambda.

---
#### Here's what I did

- Installed libpostal as specified in readme.
- Copied `/usr/local/bin` to EFS
- From Lambda changed path var
- `export LD_LIBRARY_PATH=/mnt/efs/fs1/libpostal_lib`

---
#### Here's what I got
Same old `ImportError: cannot import name '_parser'`, which tells me it still cannot find bindings. I double-checked the variable, that files are there.

I'd be nice to figure that out so people can use Lambda since it some cases it's better than ECS, especially scaling.

**Comment by manycoding** [comment]
I also tried specifying `prefix` on clean system, but `pypostal` installation fails:

```
sudo apt-get install curl autoconf automake libtool pkg-config python3-pip
pip3 install -U pip

sudo git clone https://github.com/openvenues/libpostal
cd libpostal
sudo ./bootstrap.sh
sudo ./configure --datadir=/mnt/efs/libpostal_data --prefix=/mnt/efs/libpostal_lib
sudo make -j4
sudo make install
sudo ldconfig
export LD_LIBRARY_PATH=/mnt/efs/libpostal_lib/lib

pip install postal
```
Here're flags:
```ubuntu:/mnt/efs$ pkg-config --cflags libpostal
-I/mnt/efs/libpostal_lib/include
ubuntu:/mnt/efs$ pkg-config --libs libpostal
-L/mnt/efs/libpostal_lib/lib -lpostal
ubuntu:/mnt/efs$ pkg-config --cflags --libs libpostal
-I/mnt/efs/libpostal_lib/include -L/mnt/efs/libpostal_lib/lib -lpostal
```

I ran with `sudo` because on EC2 root is disabled and `ubuntu` user has no permissions to write on EFS.

**Comment by manycoding** [comment]
I also tried another approach from here https://github.com/openvenues/pypostal/issues/58:

I downloaded a built a sdist from patched code, installed it on lambda
Saved `LIBPOSTAL_DATA_DIR` and `LD_LIBRARY_PATH` variables
*.so files are on EFS in LD_LIBRARY_PATH directory

**Comment by manycoding** [comment]
Hi @albarrentine , I am not sure if this issue belongs here or to https://github.com/openvenues/pypostal?

**Comment by manycoding** [comment]
Hey @uzadude, I see you had a similar issue - could you have a look please?

**Comment by uzadude** [comment]
Hi, my patch was about changing the location os the data-dir. It looks like your error is even before that.
here are my files in the install folder:
```
>>> import os; os.listdir("/usr/lib64/python2.7/site-packages/postal/")
['tokenize.pyc', 'expand.pyc', 'normalize.pyc', '__init__.pyc', 'tests', 'normalize.py', '_tokenize.so', '_expand.so', 'near_dupe.py', 'token_types.py', '_normalize.so', 'expand.py', 'parser.pyc', 'dedupe.py', 'utils', 'token_types.pyc', '_dedupe.so', 'near_dupe.pyc', 'parser.py', 'tokenize.py', '_parser.so', 'dedupe.pyc', 'pyutils.h', '_token_types.so', '_near_dupe.so', '__init__.py']
```
you can see that they look a little different, hope that helps..

**Comment by manycoding** [comment]
Hey, I found the solution - it's in Readme here https://github.com/manycoding/address-parser/blob/master/README.md
In short, the approach with patched libpostal from openvenues/pypostal#58 worked.
The thing I was stuck is mostly my little knowledge about the subject.

`cannot import name '_parser'` means it cannot find C bindings which are created during `pypostal` installation.

**Comment by hsvvijay** [comment]
>     * var

Hi, Can you please help me with this? I am trying to follow the same steps in Amazon Linux instance - but in the /usr/local/bin directory, I have hardly 50 KB files. I am not able to find a working solution any where

Please help

**Comment by hsvvijay** [comment]
> 
> 
> I also tried specifying `prefix` on clean system, but `pypostal` installation fails:
> 
> ```
> sudo apt-get install curl autoconf automake libtool pkg-config python3-pip
> pip3 install -U pip
> 
> sudo git clone https://github.com/openvenues/libpostal
> cd libpostal
> sudo ./bootstrap.sh
> sudo ./configure --datadir=/mnt/efs/libpostal_data --prefix=/mnt/efs/libpostal_lib
> sudo make -j4
> sudo make install
> sudo ldconfig
> export LD_LIBRARY_PATH=/mnt/efs/libpostal_lib/lib
> 
> pip install postal
> ```
> 
> Here're flags:
> 
> ```
> ubuntu:/mnt/efs$ pkg-config --cflags libpostal
> -I/mnt/efs/libpostal_lib/include
> ubuntu:/mnt/efs$ pkg-config --libs libpostal
> -L/mnt/efs/libpostal_lib/lib -lpostal
> ubuntu:/mnt/efs$ pkg-config --cflags --libs libpostal
> -I/mnt/efs/libpostal_lib/include -L/mnt/efs/libpostal_lib/lib -lpostal
> ```
> 
> I ran with `sudo` because on EC2 root is disabled and `ubuntu` user has no permissions to write on EFS.



> 
> 
> I want to run a libpostal enabled code in Lambda. For that I could use EFS, the only thing which stops me is that I am not sure how to install libpostal bindings onto EFS and link them from Lambda.
> #### Here's what I did
> 
>     * Installed libpostal as specified in readme.
> 
>     * Copied `/usr/local/bin` to EFS
> 
>     * From Lambda changed path var
> 
>     * `export LD_LIBRARY_PATH=/mnt/efs/fs1/libpostal_lib`
> 
> 
> #### Here's what I got
> 
> Same old `ImportError: cannot import name '_parser'`, which tells me it still cannot find bindings. I double-checked the variable, that files are there.
> 
> I'd be nice to figure that out so people can use Lambda since it some cases it's better than ECS, especially scaling.

Hi, Can you please help me with this? I am trying to follow the same steps in Amazon Linux instance - but in the /usr/local/bin directory, I have hardly 50 KB files. I am not able to find a working solution any where

Please help
