### ISSUE TITLE
seg fault on latest build

### ISSUE THREAD

**Issue by trescube** [openvenues/libpostal#52]
I pulled the latest from master and, while it builds successfully, I get the following when trying to run the address parser:

```
admins-MacBook-Pro-4% ./src/address_parser
Loading models...
zsh: segmentation fault  ./src/address_parser
```

This is on OSX 10.11.3.

**Comment by thatdatabaseguy** [comment]
Did you run ```sudo make install``` or just ```make```? If you only run make and there's an ABI change (I'll bump versions for an API change, but likely not for ABI), it's probably linking to the installed binary.

If that doesn't work, try ```make clean``` followed by ```make``` and ```sudo make install```. Just tried on a fresh master checkout using 10.11.2 and it worked fine.

**Comment by trescube** [comment]
I ran both `make` and `sudo make install`.  I just blew away the data directory, then did a `make clean` and it's in the middle of a `make` right now.  Will let you know how it turns out.

**Comment by trescube** [comment]
That fixed it, thx!

**Comment by thatdatabaseguy** [comment]
:100:, I'll make a note about that in the README, have seen it once or twice as well.

P.S. it should be fine to keep the data directory around (re-downloading the data files can be a pain), that shouldn't affect anything. ```make clean``` and recompile is what fixes everything.
