### ISSUE TITLE
Please tag a stable version

### ISSUE THREAD

**Issue by dshafik** [openvenues/libpostal#520]
Hi!

I was checking out libpostal, and saw something that could be improved.

I have been trying to submit libpostal to the homebrew package manager for the last 2-3 weeks with little success due to the current state of libpostal releases. See: homebrew/homebrew-core#61540

The `libpostal_data` script is completely broken in the latest stable (v1.0) release, and homebrew will not accept non-stable releases; **v1.1-alpha has been tagged since May 2018 almost 2.5 years ago**, please either backport the fixes to the `libpostal_data` script to a stable 1.0.x release, or finalize the 1.1 release so that this can be included in the most popular package manager for macOS.

Thank you!

**Comment by bwitt** [comment]
hi just wanted to echo the sentiment here; a release would be very helpful!  Is there anything we can do to help?  Thanks for your hard work on this project!

**Comment by ajoga** [comment]
Duplicates #477

**Comment by marctorsoc** [comment]
tagging the main contributor @albarrentine . Hope you don't mind, but there hasn't been a release in 3 years, even though I see PRs merged from June this year. Happy to help if I can

**Comment by albarrentine** [comment]
changed the tag name to v1.1. Otherwise that sounds like an issue with homebrew.
