### ISSUE TITLE
What's the status of the project?

### ISSUE THREAD

**Issue by glebsts** [openvenues/libpostal#550]
Hello,
I am evaluating `libpostal` to be used in production system. I can see that there are many opened issues, and last pull request merged was quite a long ago. What's overall status of the maintenance? @albarrentine I've read your medium post from 2017 about v1 release.  I know many package creators have no time or ability to deal with their creations because it requires lot of time and patience. How are you? 
What's up with the future of `libpostal`?

Best regards,

**Comment by albarrentine** [comment]
I use libpostal often on tens of millions of addresses at the non-profit I work for, it's still great :).

Currently I'm mentoring/training a small group of new developers within our org one-on-one every week, which saps up most of my allotment of time, patience, and all those other virtues.

May do some revamping later this year/early next around making the address parser better on the half a percentage of parses it misses, and also acknowledge that after a decade-plus of doing this data science thing, chasing the last tenth of a point of performance can quickly turn into overfitting and diminishing returns.

The other issues folks have are typically: make it smaller, document/automate the training pipeline, or make it return probabilities. All of those are probably worthwhile.
