### ISSUE TITLE
Issue while running make command in Ubuntu

### ISSUE THREAD

**Issue by SunnySinghs** [openvenues/libpostal#558]
I'm installing the libpostal in ubuntu on EC2 instance and getting below issue while running the make command

make  all-recursive
make[1]: Entering directory '/home/ubuntu/libpostal'
Making all in src
make[2]: Entering directory '/home/ubuntu/libpostal/src'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.. -I/usr/local/include    -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-se
curity -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR='"/home/ubuntu/libpostal"' -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O0 -D LIBPOSTAL_EXPORTS   -MT li
bscanner_la-scanner.lo -MD -MP -MF .deps/libscanner_la-scanner.Tpo -c -o libscanner_la-scanner.lo `test -f 'scanner.c' || echo './'`scanner.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I.. -I/usr/local/include -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-com
pare -DLIBPOSTAL_DATA_DIR=\"/home/ubuntu/libpostal\" -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O0 -D LIBPOSTAL_EXPORTS -MT libscanner_la-scanner.lo -MD -MP -MF
 .deps/libscanner_la-scanner.Tpo -c scanner.c  -fPIC -DPIC -o .libs/libscanner_la-scanner.o
gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
make[2]: *** [Makefile:1705: libscanner_la-scanner.lo] Error 1
make[2]: Leaving directory '/home/ubuntu/libpostal/src'
make[1]: *** [Makefile:459: all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/libpostal'
make: *** [Makefile:368: all] Error 2

**Comment by cmmorrow** [comment]
I'm seeing this as well when running `make -j4` in an Ubuntu 20.04 container.

**Comment by missinglink** [comment]
You're going to have to provide more information for someone to help you.

- OS version
- Instance Config (Memory/CPU)
- Architecture (x86/ARM)
- Kernel version
- Which docker image are you using

**Comment by missinglink** [comment]
The error message above doesn't contain any clues, my suspicion is too little RAM.

**Comment by cmmorrow** [comment]
* MacOS
* CPUS: 8, RAM 32 GB, 1 TB disk
* Arch x86
* Ubuntu:20.04

I resolved the issue by following the installation instructions with the exception that I changed `make -j4` to `make`.

**Comment by missinglink** [comment]
In MacOS, what settings do you have for Docker?`Docker` > `Preferences` > `Advanced`

Try maxing out `Memory-RAM` and `CPUs-Cores`, I have the same machine and I prefer to allow Docker to use more resources than the defaults.

**Comment by SunnySinghs** [comment]
@missinglink Yes, this issue is due to memory. Thanks for the help!
