### ISSUE TITLE
make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by zffocussss** [openvenues/libpostal#595]
Hi
  hi team.when trying to install libpostal,it failed and told me "make: *** No rule to make target 'install'.  Stop."
  I am installing in dockefile

RUN git clone https://github.com/openvenues/libpostal && \
cd libpostal && \
make distclean && \
/bin/bash bootstrap.sh && \
./configure --disable-data-download --datadir=/data/ && \
make -j4 & \
make install && \
libpostal_data download all /data/ && \
ldconfig

**Comment by missinglink** [comment]
You're missing a second ampersand

**Comment by missinglink** [comment]
If you want to end execution on the first failure, it's cleaner to use `set -e` in bash at the top of your script and get rid off all the `&&`

**Comment by thebenjaminp** [comment]
Hi, I'm also getting an identical message, installing via terminal with a MacOSX M1 machine when I try and execute "make distclean."

**Comment by bdmapman** [comment]
Hello @missinglink , I am using this for a long time. Recently I am upgrading all my stuff to Ubuntu 22.04. I am also using libpostal within a docker so an automated script is needed. When I got all the errors then I started R&D using a fresh Ubuntu Image. I got few answers [here](https://github.com/openvenues/libpostal/issues/587) also

**R&D 1: using `make j4`**
OS: Ubuntu 22.04
Script:
```
mkdir /opt/libpostal_data
git clone https://github.com/openvenues/libpostal.git
cd libpostal
make distclean
./configure --datadir=/opt/libpostal_data
make -j4 
make install
```
_Result:_
`make distclean` returning
> make: *** No rule to make target 'install'. Stop.
`make j4` returning
<img width="1727" alt="CleanShot 2022-10-28 at 14 31 44@2x" src="https://user-images.githubusercontent.com/58272340/198547279-97f75ba3-2ebc-4a0e-a14b-03729c3d9c9c.png">
If I use `make j4` again it is still returning the same error.

**R&D 1: using `make j2`**
OS: Ubuntu 22.04
Script:
```
mkdir /opt/libpostal_data
git clone https://github.com/openvenues/libpostal.git
cd libpostal
make distclean
./configure --datadir=/opt/libpostal_data
make -j2 
make install
```
_Result:_
`make distclean` returning
> make: *** No rule to make target 'install'. Stop.
`make j2` returning
<img width="1727" alt="CleanShot 2022-10-28 at 14 31 44@2x" src="https://user-images.githubusercontent.com/58272340/198547279-97f75ba3-2ebc-4a0e-a14b-03729c3d9c9c.png">

If I run `make j2` after the first error then the installation is successful. 

**R&D 1: using `make j1`**
`make j1` also producing the same result as `make j2`

Please if you have time pay attention to this matter.

**Comment by missinglink** [comment]
see https://github.com/openvenues/libpostal/pull/605
