### ISSUE TITLE
Problem building with French locale

### ISSUE THREAD

**Issue by millette** [openvenues/libpostal#60]
I had an error with make, something about a date in the wrong format, since my GNU/Linux system is in French (fr-CA). The date was output in French and couldn't be parsed.

Using the following I was able to build:
```sh
LC_ALL=C make
```

**Comment by thatdatabaseguy** [comment]
Ah, that would be in the data download script (uses the curl date format, which I guess is not localized). I added an ```export LC_ALL=C``` to the download script so just plain ```make``` should work in the future.
