### ISSUE TITLE
French fail?

### ISSUE THREAD

**Issue by okeyes-r7** [openvenues/libpostal#61]
Using the latest version of the models and the classic "Quatre-vignt-douze Ave des Champs-Élysées" it's not recognising the 'vignt'; I get  "4-vignt-12 avenue des champs-elysees" as output.

**Comment by thatdatabaseguy** [comment]
Hey Oliver (new handle?) - a native French speaker pointed out that it's supposed to be "vingt", not "vignt". I've updated all of the examples and bindings with the correct spelling although I expect "vignt" to linger for a while.

**Comment by okeyes-r7** [comment]
Aha, doy. New job! Okay, cool; will update my tests accordingly :).
