### ISSUE TITLE
Parsing Problem:  Via Divisone Folgore 5/B Vicenca 36100 (italy)

### ISSUE THREAD

**Issue by schikla** [openvenues/libpostal#613]
Hi!

I was checking out libpostal, and saw something that could be improved.

---
#### My country is
Austria

---
#### Here's how I'm using libpostal
address_parser.exe (latest version 1.1)

---
#### Here's what I did
> Via Divisone Folgore 5/B Vicenca 36100

---
#### Here's what I got
Result:

{
  "road": "via divisone folgore",
  "house_number": "5/b",
  "road": "vicenca",
  "postcode": "36100"
}

---
#### Here's what I was expecting
Result:

{
  "road": "![OpenStreetMap](https://user-images.githubusercontent.com/8876246/210805232-bf3a57c4-fb2e-4563-83a7-6fc8d4e2a1b0.JPG)",
  "house_number": "5/b",
  "city": "vicenca",
  "postcode": "36100"
}

---
#### For parsing issues, please answer "yes" or "no" to all that apply.

- Does the input address exist in [OpenStreetMap](https://openstreetmap.org)?
https://www.openstreetmap.org/search?query=Vicenca%2036100#map=12/45.5463/11.5504
-- see attachment
https://www.google.at/maps/place/Via+Divisione+Folgore,+5b,+36100+Vicenza+VI,+Italien/@45.5591794,11.5248776,19z/data=!4m5!3m4!1s0x477f33ef7ece3523:0xfcbfc6ed132540a7!8m2!3d45.5592419!4d11.5248761

- Do all the toponyms exist in OSM (city, state, region names, etc.)?

- If the address uses a rare/uncommon format, does changing the order of the fields yield the correct result?

- If the address does not contain city, region, etc., does adding those fields to the input improve the result?
and libpostal's training addresses. -->
- If the address contains apartment/floor/sub-building information or uncommon formatting, does removing that help? Is there any minimum form of the address that gets the right parse?
asking for help can save time for maintainers and improve your understanding of the project. -->

---
#### Here's what I think could be improved
???

Kind Regards
Klaus

**Comment by robvadai** [comment]
The name of the city is Vicen**_z_**a so you have a typo.
It works with that correctly:
```
>>> parse_address('Via Divisone Folgore 5/B Vicenza 36100')
[('via divisone folgore', 'road'), ('5/b', 'house_number'), **_('vicenza', 'city')_**, ('36100', 'postcode')]
>>> parse_address('Via Divisone Folgore 5/B Vicenca 36100')
[('via divisone folgore', 'road'), ('5/b', 'house_number'), ('vicenca', 'road'), ('36100', 'postcode')]
```

Sure it'd be good if the library would understand typos but I guess that's not a concern it addresses. You may want to run a find/replace type operation to find typos using the [Metaphone](https://en.wikipedia.org/wiki/Metaphone) library or similar one.

**Comment by schikla** [comment]
Absolutely!
It was an error on the registration certificate.
After correcting the city name, parsing was excellent.

{"road": "Via Divisone Folgore", "house_number": "5/B", "city": "Vicenza", "postcode": "36100"}
