### ISSUE TITLE
Provide updated data of OSM to libpostal model

### ISSUE THREAD

**Issue by krishbhk** [openvenues/libpostal#635]
Hi!

I was looking into libpostal, I wanted to retrain the existing model on a new set of data to see the results. I couldn't find any document regarding the retraining the existing model and how to prepare a custom dataset or the dat files which are generated at time of installation

**Comment by krishbhk** [comment]
Since the last data of the OSM is of 2017, Is it possible to update the training data to the present one. and retrain the existing model?

**Comment by brianmacy** [comment]
https://github.com/openvenues/libpostal#installation-with-an-alternative-data-model

**Comment by krishbhk** [comment]
Hi brianmacy,
Thank for the response.
I saw the senzing model, but I wanted to know how can I retrain the existing model, I've a CSV file of addresses as well as new data present in OSM compared to one present in 2017. Please correct me if I'm wrong, but it seems the last data pulled from OSM and Open Address was 2017. 
I'm also trying to find how the .dat files are being created and their schema which are downloaded at the time of installation

**Comment by brianmacy** [comment]
The Senzing data model was pulled from very recent data (late 2022 at least).  BTW it took us 9+ month to figure out how to train a new model and it is kludged together... takes about a week to run on the fastest machine I could put together.  Hoping some day to be able to provide a way for others to reasonably train but right now our efforts are on improving the model for users.
