### ISSUE TITLE
Italia returns as country while not iso 3166

### ISSUE THREAD

**Issue by manycoding** [openvenues/libpostal#644]
Hi!

I was checking out libpostal, and saw something that could be improved.
E.g. for a simple address `"Via Mazzacavallo, 8 43122 Parma PR Italia"` lib postal returns country as Italia, but that's not 3166

I'd expect Italy.

**Comment by albarrentine** [comment]
libpostal is an NLP model that parses the input given. Cross-lingual normalization of country names/ISO 3166 code lookups are a somewhat easier database-oriented task and can be done e.g. with GeoNames, etc.
