### ISSUE TITLE
Apartment units

### ISSUE THREAD

**Issue by rbrtmrtn** [openvenues/libpostal#65]
I was wondering if there's currently support for secondary addresses such as apartments, condos, and offices, or if that's outside the scope of `libpostal`. When I run an address like `1500 CHESTNUT ST APT B, PHILADELPHIA, PA` through `address_parser` I get:

```
Result:

{
  "house_number": "1500",
  "road": "chestnut st apt b",
  "city": "philadelphia",
  "state": "pa"
}
```

For my particular purposes it would be great if there were distinct tags for the unit designator and unit num.

Thanks!

**Comment by thatdatabaseguy** [comment]
It's not implemented yet as there's very little sub-building information available in OSM addresses. I'm working on a branch at the moment called [parser-data](https://github.com/openvenues/libpostal/tree/parser-data) which generates apartment numbers, PO boxes, etc. in multiple languages and a variety of formats to supplement the OSM addresses.

The new model's not usable at the moment, but once it's trained there will be a distinct tag for "unit" and the parser shouldn't have trouble with sub-building addresses. It's a single tag. Designator/number as a pattern doesn't really cover all unit types (English counter examples: "penthouse" or something like "top right" as seen in Edinburgh). Still, it would be very easy to strip out words like "apt" from the full unit string using a regex and the fairly comprehensive libpostal [dictionaries](https://github.com/openvenues/libpostal/blob/parser-data/resources/dictionaries/en/unit_types_numbered.txt).

**Comment by rbrtmrtn** [comment]
Good to hear, I'll keep an eye out for the new model. Thanks!
