### ISSUE TITLE
A space in the city confused the parser

### ISSUE THREAD

**Issue by CamdenParker** [openvenues/libpostal#675]
Hi!

I was checking out libpostal, and saw something that could be improved.

---
#### My country is
USA

---
#### Here's how I'm using libpostal

I am using it in support of entity resolution amongst a myriad of environmental, health and safety data sources.

---
#### Here's what I did:

```
 ./src/address_parser
Loading models...

Welcome to libpostal's address parser.

Type in any address to parse and print the result.

Special commands:
.exit to quit the program

> 13775 CLARK RD, ROSE MOUNT, MN
```

---
#### Here's what I got:
The parser seemingly preferred to create a street name with a comma in it rather than a city with two words?

```
Result:

{
  "house_number": "13775",
  "road": "clark rd rose",
  "city": "mount",
  "state": "mn"
}
```

---
#### Here's what I was expecting:
```
{
  "house_number": "13775",
  "road": "clark rd",
  "city": "rose mount",
  "state": "mn"
}
```

---
#### For parsing issues, please answer "yes" or "no" to all that apply.

- Does the input address exist in [OpenStreetMap](https://openstreetmap.org)? No
  
- Do all the toponyms exist in OSM (city, state, region names, etc.)?
  
- If the address uses a rare/uncommon format, does changing the order of the fields yield the correct result?
  
- If the address does not contain city, region, etc., does adding those fields to the input improve the result?
   No
```
> 13775 CLARK RD, ROSE MOUNT, MN, USA

Result:

{
  "house_number": "13775",
  "road": "clark rd rose",
  "city": "mount",
  "state": "mn",
  "country": "usa"
}

> 13775 CLARK RD, ROSE MOUNT, MN 55068, USA

Result:

{
  "house_number": "13775",
  "road": "clark rd rose",
  "city": "mount",
  "state": "mn",
  "postcode": "55068",
  "country": "usa"
}

> 13775 CLARK RD, ROSE MOUNT, MN 55068

Result:

{
  "house_number": "13775",
  "road": "clark rd rose",
  "city": "mount",
  "state": "mn",
  "postcode": "55068"
}
```
- If the address contains apartment/floor/sub-building information or uncommon formatting, does removing that help? Is there any minimum form of the address that gets the right parse?
  
```
> 13775 CLARK RD, ROSEMOUNT, MN

Result:

{
  "house_number": "13775",
  "road": "clark rd",
  "city": "rosemount",
  "state": "mn"
}
```
---
#### Here's what I think could be improved:

Thinking maybe there were some edge cases in the training data where a street name came after a comma? Idrk

**Comment by CamdenParker** [comment]
Worked like a charm. Thank you sir

**Comment by brianmacy** [comment]
Great to hear.  If you interested in any help with ER, let me know :)
