### ISSUE TITLE
'saint' vs 'street'

### ISSUE THREAD

**Issue by easherma** [openvenues/libpostal#73]
New to this library, so forgive if this has been addressed. (no pun intended! ;-p) 

After an address has been expanded, whats the expected use for the expanded results? 

Example, a common use case seems to expand 'St' to 'saint' or 'street'. If I'm trying to expand addresses in bulk, I'd want to programmatically choose an option. I would consider 'street' to be more appropriate the vast majority of the time, but I can't go through and choose manually for each entry.

**Comment by thatdatabaseguy** [comment]
The goal of expansion is not to choose the best result, but to aid in things like deduping and geocoding, so if ```len(set(expand_address(a1)) & set(expand_address(a2))) > 0``` (the equivalent of a JOIN in SQL), they're effectively dupes. Ignoring the ambiguity seems weird at first, but the idea here is to just index all the strings returned by libpostal, run the exact same code at query time and issue multiple queries to the index.

There's been some interest in picking a "single best" result for database standardization, map display, etc. (or a ranked list/probability distribution) but for most applications it's not really necessary. Disambiguation is a solvable problem, just not one I've had time to work on during my contract with Mapzen.

**Comment by easherma** [comment]
Super helpful, thanks!
