### ISSUE TITLE
Invalid output for dutch address with house number addition indicating the ground floor

### ISSUE THREAD

**Issue by DaanBiesterbos** [openvenues/libpostal#75]
Hi :-)  

I was testing libpostal against a bunch of addresses. I am very happy with the results for the most part. 
I did encounter a problem with parsing a particular type of address that is actually pretty common in the Netherlands. The addresses I used for this test come from official documents of a dutch court so I expect this problem to occur in real life as well. 

This is the address I parsed using the ./address_parser shell. Translated this street can be read as: "Olympia 1A ground floor".
`> Olympia 1 A begane gro`

Result:

``` json
{
  "road": "olympia",
  "house_number": "1 a",
  "road": "begane gro"
}

```

The engine got it half right. (impressive) But in my humble opinion two things go wrong.
One is that I would expect "begane gro" as  a house number addition.  I am not sure if that concept even exists internationally. Another issue is that this json structure is not valid. If I would read this document I would get  "begane gro" as the value for road.  I would be most happy if I would get both values separately.  But the fact that a less important value can override the actual street name seems like something that really need to be fixed..

**Comment by thatdatabaseguy** [comment]
Hoi Daan,

Dutch is actually the 3rd most widely used language in OSM addresses after German and English, so it may be that every street address in the Netherlands is somewhere in the training set.

For parsing that style of address, you are in luck. There's a new version of the parser in the works which can handle all kinds of sub-building information and has new tags like "level", "unit", etc.

The basic problem was that OpenStreetMap only really gives us street names and house numbers, so expressions like "begane grond", "verdieping 3", "apt 21", "kamer 402", etc. don't make it into the training data (and so the current parser doesn't know what to do with them, might as well be street names).

For the new parser, the observation was that most sub-building address fields like apartment numbers, etc. follow a small number of predictable patterns and we can actually generate those fields at random with many variations and add them to the training addresses. I'm personally writing the configs for the most common ~20 languages in OSM including [a Dutch config](https://github.com/openvenues/libpostal/blob/parser-data/resources/addresses/nl.yaml).

I'll update this and a number of other issues when the new parser is ready.

./al

**Comment by DaanBiesterbos** [comment]
Awesome. Thanks for the response.
And sorry for my late response..... I did not notice before.

**Comment by DaanBiesterbos** [comment]
Oh and let me know if you need help with the dutch language. If you run into language barriers I will gladly assist.

**Comment by thatdatabaseguy** [comment]
Hey @DaanBiesterbos, libpostal 1.0 has been released and can parse addresses like the above correctly (new tags for "unit", "level", etc.):

```
> Olympia 1 A begane gro

Result:

{
  "road": "olympia",
  "house_number": "1 a",
  "level": "begane gro"
}
```

Added this to our demo / test cases.
