### ISSUE TITLE
*** glibc detected *** /home/admin/libpostal/src/.libs/lt-address_parser: free(): invalid pointer: 

### ISSUE THREAD

**Issue by SuPa86000** [openvenues/libpostal#77]
Hello,

I have an error on a VirtualBox Debian machine running under Mac OSX El Captain 10.11.5.

> ~/libpostal/src$ ./address_parser
> Loading models...
> **\* glibc detected **\* /home/admin/libpostal/src/.libs/lt-address_parser: free(): invalid pointer: 0x00007f9368153fa8 ***
> ======= Backtrace: =========
> /lib/x86_64-linux-gnu/libc.so.6(+0x75be6)[0x7f9367e42be6]
> /lib/x86_64-linux-gnu/libc.so.6(cfree+0x6c)[0x7f9367e4798c]
> /home/admin/libpostal/src/.libs/libpostal.so.0(trie_destroy+0x20)[0x7f9368381b90]
> /home/admin/libpostal/src/.libs/libpostal.so.0(geodb_destroy+0x2d)[0x7f9368391bdd]
> /home/admin/libpostal/src/.libs/libpostal.so.0(geodb_init+0x350)[0x7f9368391fb0]
> /home/admin/libpostal/src/.libs/libpostal.so.0(geodb_load+0x9)[0x7f9368392029]
> /home/admin/libpostal/src/.libs/libpostal.so.0(libpostal_setup_parser+0xb)[0x7f936837528b]
> /home/admin/libpostal/src/.libs/lt-address_parser[0x4017da]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd)[0x7f9367debead]
> /home/admin/libpostal/src/.libs/lt-address_parser[0x401af1]
> ======= Memory map: ========
> 00400000-00406000 r-xp 00000000 fe:00 435608                             /home/admin/libpostal/src/.libs/lt-address_parser
> 00605000-00606000 rw-p 00005000 fe:00 435608                             /home/admin/libpostal/src/.libs/lt-address_parser
> 01648000-03400000 rw-p 00000000 00:00 0                                  [heap]
> 7f9360000000-7f9360021000 rw-p 00000000 00:00 0 
> 7f9360021000-7f9364000000 ---p 00000000 00:00 0 
> 7f9366b80000-7f936762e000 rw-p 00000000 00:00 0 
> 7f936762e000-7f9367643000 r-xp 00000000 fe:00 581636                     /lib/x86_64-linux-gnu/libgcc_s.so.1
> 7f9367643000-7f9367843000 ---p 00015000 fe:00 581636                     /lib/x86_64-linux-gnu/libgcc_s.so.1
> 7f9367843000-7f9367844000 rw-p 00015000 fe:00 581636                     /lib/x86_64-linux-gnu/libgcc_s.so.1
> 7f9367844000-7f93678c5000 r-xp 00000000 fe:00 581637                     /lib/x86_64-linux-gnu/libm-2.13.so
> 7f93678c5000-7f9367ac4000 ---p 00081000 fe:00 581637                     /lib/x86_64-linux-gnu/libm-2.13.so
> 7f9367ac4000-7f9367ac5000 r--p 00080000 fe:00 581637                     /lib/x86_64-linux-gnu/libm-2.13.so
> 7f9367ac5000-7f9367ac6000 rw-p 00081000 fe:00 581637                     /lib/x86_64-linux-gnu/libm-2.13.so
> 7f9367ac6000-7f9367bae000 r-xp 00000000 fe:00 780302                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17
> 7f9367bae000-7f9367dae000 ---p 000e8000 fe:00 780302                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17
> 7f9367dae000-7f9367db6000 r--p 000e8000 fe:00 780302                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17
> 7f9367db6000-7f9367db8000 rw-p 000f0000 fe:00 780302                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.17
> 7f9367db8000-7f9367dcd000 rw-p 00000000 00:00 0 
> 7f9367dcd000-7f9367f4e000 r-xp 00000000 fe:00 581643                     /lib/x86_64-linux-gnu/libc-2.13.so
> 7f9367f4e000-7f936814e000 ---p 00181000 fe:00 581643                     /lib/x86_64-linux-gnu/libc-2.13.so
> 7f936814e000-7f9368152000 r--p 00181000 fe:00 581643                     /lib/x86_64-linux-gnu/libc-2.13.so
> 7f9368152000-7f9368153000 rw-p 00185000 fe:00 581643                     /lib/x86_64-linux-gnu/libc-2.13.so
> 7f9368153000-7f9368158000 rw-p 00000000 00:00 0 
> 7f9368158000-7f936815d000 r-xp 00000000 fe:00 147519                     /usr/lib/libsnappy.so.1.1.3
> 7f936815d000-7f936835c000 ---p 00005000 fe:00 147519                     /usr/lib/libsnappy.so.1.1.3
> 7f936835c000-7f936835d000 r--p 00004000 fe:00 147519                     /usr/lib/libsnappy.so.1.1.3
> 7f936835d000-7f936835e000 rw-p 00005000 fe:00 147519                     /usr/lib/libsnappy.so.1.1.3
> 7f936835e000-7f93686c9000 r-xp 00000000 fe:00 435581                     /home/admin/libpostal/src/.libs/libpostal.so.0.0.0
> 7f93686c9000-7f93688c8000 ---p 0036b000 fe:00 435581                     /home/admin/libpostal/src/.libs/libpostal.so.0.0.0
> 7f93688c8000-7f9368d19000 rw-p 0036a000 fe:00 435581                     /home/admin/libpostal/src/.libs/libpostal.so.0.0.0
> 7f9368d19000-7f9368d39000 r-xp 00000000 fe:00 581655                     /lib/x86_64-linux-gnu/ld-2.13.so
> 7f9368e0c000-7f9368f30000 rw-p 00000000 00:00 0 
> 7f9368f35000-7f9368f38000 rw-p 00000000 00:00 0 
> 7f9368f38000-7f9368f39000 r--p 0001f000 fe:00 581655                     /lib/x86_64-linux-gnu/ld-2.13.so
> 7f9368f39000-7f9368f3a000 rw-p 00020000 fe:00 581655                     /lib/x86_64-linux-gnu/ld-2.13.so
> 7f9368f3a000-7f9368f3b000 rw-p 00000000 00:00 0 
> 7ffc7b677000-7ffc7b698000 rw-p 00000000 00:00 0                          [stack]
> 7ffc7b6de000-7ffc7b6df000 r-xp 00000000 00:00 0                          [vdso]
> ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
> Abandon

**Comment by thatdatabaseguy** [comment]
So that looks like an out-of-memory condition. I would recommend giving the VirtualBox at least 4GB to run libpostal plus the OS, application, etc.

There's an example Vagrantfile that may be helpful here: https://github.com/riordan/vagrant-libpostal

**Comment by SuPa86000** [comment]
This does not change the problem, I still have the same error with 4GB.

**Comment by thatdatabaseguy** [comment]
Ok, it might be the data files. Can you check the output of ```du -h $LIBPOSTAL_DATA_DIR``` where LIBPOSTAL_DATA_DIR is whatever you passed in to --datadir during configure? There should be ~2.2G of model files in that dir. If not, make sure there's enough space on the disk, then try deleting that directory and re-running ```make``` to download them again.

**Comment by thatdatabaseguy** [comment]
Assuming this can be closed?

**Comment by thatdatabaseguy** [comment]
No response, closing.
