### ISSUE TITLE
street type mismatch

### ISSUE THREAD

**Issue by h4ck3rm1k3** [openvenues/libpostal#83]
These addresses where the suite is I or J are being treated as junction or island or interstate

SHIRLEY LANE J-8, lawrence, nj => ["shirley lane j-8 lawrence nj", "shirley lane j-8 lawrence new jersey", "shirley lane j 8 lawrence nj", "shirley lane j 8 lawrence new jersey", "shirley lane junction 8 lawrence nj", "shirley lane junction 8 lawrence new jersey"]

**Comment by thatdatabaseguy** [comment]
Tokens like "I-80", "I35", etc. are supposed to expand to interstate, same with "J-8" which may actually mean junction in some contexts. In expand_address, libpostal doesn't know which components are roads vs. sub-building identifiers, so its default behavior with no options specified is to use the expansions that apply to street, unit, and venue names. With very short abbreviations like the letter "i" which can also be someone's initial or part of a venue name that's in a different language, etc. libpostal also returns a version of the string with no expansion applied. The goal of expand_address is simply that one of the expansions is correct so it will match in a search or a SQL JOIN.

When the new parser is out (trained on units, suite numbers, etc.), you could first parse the address and only apply ADDRESS_UNIT expansions to the unit, which would only return the first 2-4 expansions depending on which options were passed.

**Comment by Noodle05** [comment]
Hi thatdatabaseguy,

Do you have est. on when will libpostal support suite/unit?

Thanks

Noodle

**Comment by thatdatabaseguy** [comment]
@Noodle05 not sure yet on the full release. The sub-building support and expanded coverage caused a few types of regressions which my current experiments are attempting to fix. There is an early version of the new model available at: https://libpostal.s3.amazonaws.com/mapzen_sample/parser_full.tar.gz, if you want to try it out. To use that (doesn't require switching branches or anything, it's the same model in master trained on new data), just unpack the contents of the tarball into $DATA_DIR/libpostal/address_parser where $DATA_DIR is whatever you passed in during configure, default is /usr/local/share I believe. 

Note: that build only includes units in English and Spanish. There's a fuller training set building at the moment which includes units in the [35 languages listed here](https://github.com/openvenues/libpostal/tree/parser-data/resources/addresses), added in order of address frequency in OSM and how common sub-building addresses are in countries that speak each language.

**Comment by Noodle05** [comment]
Great, thanks for quick response.

Just test with few US addresses, and "unit" was parsed properly.

Thanks

Noodle

**Comment by Noodle05** [comment]
Can we create bug for this feature? Or wait till it got released?

I'm seeing address with "Apt. xxx", where "Apt." should be part of "unit", been parsed as "Apt." is part of road. "unit" still filled with "xxx", which is correct.

**Comment by thatdatabaseguy** [comment]
I'll have a look at it, but it's something simple related to normalization of the "." at the end of "Apt." Try typing just "Apt" with no period and that should be close to how the final model will work.

**Comment by Noodle05** [comment]
Yeah, you are right, "Apt" works, "Apt." not working.

Thanks

**Comment by thatdatabaseguy** [comment]
@Noodle05, libpostal 1.0 has been released. Apartments/suites, etc. are covered and the final period should no longer make a difference.
