### ISSUE TITLE
node.js wrapper

### ISSUE THREAD

**Issue by dianashk** [openvenues/libpostal#9]
Please... :ice_cream: with a :cherries: on top

**Comment by thatdatabaseguy** [comment]
For sure. Will take a look after the C address parser is finished. Node extensions are slightly less straightforward than Python, Go, Ruby, etc. although I think for something CPU-bound like libpostal it's just async boilerplate.

**Comment by thatdatabaseguy** [comment]
Et voila! https://github.com/openvenues/node-postal

**Comment by riordan** [comment]
Awesome! Works well for me (thought not by any means a node expert).
